---
title: "Learning Checks Lesson 19"
---

## Setup

The `math300` package will be needed for lessons 20 through 39.

```{r message=FALSE}
library(math300)
```


## 19.1 (Objective 2)

What are the two settings for decision making that we cover in this course?

Give an example of each.

### Solution

(1) Prediction and (2) Relationship

i. What will be the sales price of this house? *"This house" is a shorthand way of saying "a house with these attributes." The sales price will be the output of a prediction function that takes the various attributes as input and produces a sales price as output.*

ii. If I look for a house with an additional bathroom, how much will that change the sales price? *This asks for the relationship between number of bathrooms and sales price.*

----------

## 19.2 (Objective 2)

For each of these research questions, say whether it is a prediction setting or a relationship setting.

i. What's the risk of falling ill? 
ii. How will the risk of falling ill change if we eat more broccholi? 
iii. Is there any reason to believe, based on the evidence at hand, that we should look more deeply into the possible benefits of broccholi?



### Solution

i. Prediction
ii. Relationship
iii. Relationship


--------

## 19.3

Fit a model to some data. Write down the function implied by the coefficients.

Evaluate the function for:

i. a=7, b=9
ii. and so on.


### Solution

--------

## 19.4

About the summarization of models. Pipe the model fit into any of four functions:

i. `%>% coefficients()`
ii. `%>% broom::tidy()`
iii. `%>% rsquared()`
iv. `%>% confint()`

REDO `confint()` so that the columns are named `lower`, `middle`, `upper`

### Solution


--------
