---
title: "Census Project Proposal"
author: "Daniel Kaplan"
output: pdf_document
---

## Overview

### Data transcription

Each student will be given a 1940 Census "Population Schedule." 

[Example of a Population Schedule](https://dtkaplan.github.io/Math-300R/www/c1940_famousmo_truman.pdf)

From the Population Schedule, the student will construct two data frames:

1. Households. We will provide them with a Google Sheets template. They will put in one line for each household. (Include reference to the "Sheets" data frame and a unique ID (within the sheet) for each household.)

2. Individuals. Data on a line-by-line basis from the Population Schedule. Household info should be a reference to the Households table.

The instructors will provide a third table already filled out:

3. Sheets. Basic information for each individual Population Schedule.

### Data wrangling

Instructors will provide some **simple** querying questions. Students should try to answer them from their own Individuals table. (Maybe one question will involve joining with the Households table.) 

Example: How many children in each household?

If the data are not organized in a manner suitable to answer the question, the student will explain what about the student's organization prevented answering the question and what they would change about the organization in order to make it feasible to answer the question. (This re-organization does not need to be done.)

### Documents

- Student access to Population Schedules will be by URL
    a. We will provide some generic sheets as listed in the Sources section, below.
    b. We will ask each student to pick a state, county, and town where they live now or where their grandparents lived. Then the instructors will collect those Population Schedules from the <familysearch.org> site, making them available as PDF or image files via URL.

- Student Household and Individual tables will be in Google Sheets (or some Microsoft equivalent, if available) and brought into R via a URL.
- Deliverable: An RMD file with the commands to read in the student's table and the answers to the queries. We will provide a template with the queries and the commands to read from the Household and Individual spreadsheets.


## Instructor tasks

1. For each student, instructors create a Google Spreadsheet with the Households template and an Individuals template (with variable names).

2. Produce an RMD template that 
    i. Lists the URLs for the Population Schedules
    ii. Provides the code to read in from Google sheets.
 
3. Introduce the project in class, with particular emphasis on the two different *units of observation*, households and individuals, in the Population Schedules.
    i. First, distinguish between quantitative and categorical variables
    ii. For categorical variables, make a list of the allowed levels. They can determine their own encoding.
    iii. Point out that when legibility is an issue, the student should do his or her best.
    
4. Review the submitted spreadsheets and queries in class. 
    




## Sources
 
- Geographically sorted sheets for all states, [familysearch.org]( https://www.familysearch.org/ark:/61903/3:1:3QSQ-G9MR-8XN?i=5&wc=QZXG-LF1%3A790103801%2C794825901%2C794868201%2C951699401&cc=2000219). My account is dtkaplan@gmail.com with password saved on Google.

    a. Colorado Springs

- Missouri census sheets from <https://www.sos.mo.gov/records/archives/census/pages/census1940_famousmo> for selected famous people.

    a. Yogi Berra---baseball
    b. Chuck Berry---Rock and roll legend
    c. Joe Garagiola---baseball
    d. Lizzy Marshall---last surviving child of Dred and Harriet Scott
    e. Harry Truman---At the time, a US Sendator
    f. Laura Ingalls Wilder---author of the *Litle House* series.
    
- Images from sundry places

    a. Androscoggin, ME
    b. Chicago, IL
    c. Dearborn, MI
    d. Lincoln county, AR
