---
title: "Stat 300 objectives vs Stat 300R"
author: "Daniel Kaplan"
date: "As of Sept. 14, 2022"
---

------------------------------

## Lesson 19

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 19
1. Explain the need for randomization in sampling.

2. Explain the impact of sample size on the sample distribution and number of replications on the sampling procedure.

3. Using a sampling distribution, make decisions about the population. In other words, understanding the effect of sampling variation on our estimates.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 19

1. Correctly use and explain the terms accuracy and precision and the technical terms bias and variance. 

2. Carry out (using software) a multiple regression and interpret the coefficients as marginal effects. 

3. Demonstrate sampling variation using sub-sampling on simple and multiple-regression model coefficients.
:::

::::


------------------------------

## Lesson 20

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 20

1. Know and correctly use the terminology and notation for the sampling concepts such as population, census, point estimate, biased, etc.

2. Explain the impact of sample size on the sample distribution and number of replications on the sampling procedure.

3. Use and explain the terms accuracy and precision in the context of sampling.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 20

#. Explain the meaning of "confounding" and give story examples of it.

#. Understand format of DAGs and interpret a DAG in terms of sets of direct causal relationships.

#. Identify when a DAG implies confounding.

:::

::::



------------------------------

## Lesson 21

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 21

1. Given a sampling scenario, discuss issues such as accuracy and precision as they relate to generalization to the population of interest.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 21

1. Simulating simple DAGs.

2. Construct regression models on simulated data and interpret coefficients as consistent or inconsistent with the generating DAG.


:::

::::



------------------------------

## Lesson 22

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 22

1. Explain the central limit theorem.

2. For a normal distribution, use `R` to find probabilities and percentiles.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 22 Prediction 1

#. Using software, predict the output that will correspond to an input for a given model. Interpret this in the context of a prediction interval.

#. Graph and interpret the prediction function and prediction confidence bands on low-order linear regression models.


:::

::::



------------------------------

## Lesson 23

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 23

1. Explain the concept of a bootstrap distribution using proper terminology and notation.

2. Use `R` to find the bootstrap distribution of a sample statistic.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 23 Prediction 2

#. Divide prediction confidence bands into a "model uncertainty" component and a "residual" component based on shape and sample size $n$. 

#. Calculate from model residuals the residual component of an (in-sample) prediction error from a regression model.

#. Explain why the mean-square residual and not the mean residual is a suitable measure of the precision (variance) of a prediction from a given model.
:::

::::



------------------------------

## Lesson 24

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 24

1. Explain how to construct a confidence interval using both the percentile method and the standard error method including assumptions. *DK note: Unless you want to emphasize the normal distribution, this is a technical issue and shouldn't be prioritized.

2. Explain how changing the confidence level impacts the width of a confidence interval.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 24 Prediction 3

#. Use provided deterministic models to generate simulated data and add noise of a specified magnitude to the output to produce simulated data containing inputs and outputs.

#. Compare regression results on simulated data to parameters of the simulation (including the amount of noise added to the simulation.) 

#. Show that in-sample prediction error provides a low-biased estimate of added noise.

:::

::::



------------------------------

## Lesson 25

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 25

1. Construct bootstrap percentile and standard error confidence intervals for a single mean or median using the infer package.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 25 Prediction 4

#. Divide data into "training" and "testing" sets.

#. Calculate out-of-sample prediction error. 

#. Qualitatively describe relationship among sample size $n$, number of parameters $p$, and the calculated in-sample prediction error.

(Note in draft: Later, in hypothesis testing, return to out-of-sample prediction error as analogous to replicating results to establish significance.)
:::

::::



------------------------------

## Lesson 26

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 26

1. Correctly interpret a confidence interval to include identifying incorrect statements.

2. Explain the factors that impact the width of a confidence interval.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 26 Classifiers 1

#. Identify structure of data needed to build a classifier.

#. Using software, construct a yes/no classifier based on logistic regression (with a fixed threshold, say 50%). 

#. Cross-tabulate classifier results to calculate true and false positive and negatives. Interpret performance based on "accuracy," "false positive" and "false negative" rates, "sensitivity," and "specificity."


<!-- call measured predictive quantities M -->



:::

::::




------------------------------

## Lesson 27

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 27

1. Calculate, using both percentile and standard error methods, confidence intervals for a difference of two proportions.

2. Calculate a normal-based, theory-based, confidence interval for a single proportion or mean.

3. Correctly use all terms and notation to include standard error, margin of error, sampling distribution, and bootstrap distribution.

4. Compare and contrast sampling distribution and bootstrap distribution.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 27 Classifiers 2


#. Distinguish between probability of D/Not given + result and the probability of + result given D/Not. Identify which probability type is appropriate for a given purpose.

#. Understand the role of prevalence in shaping probs of true/false given positive and of true/false given negative.


:::

::::




------------------------------

## Lesson 28

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 28

No items listed.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 28 Classifiers 3

Determining sensitivity and specificity clinically using known 

Probability inversion: Using sensitivity and specificity to update prevalence. Bayes formula written in terms of sensitivity and specificity.

<!-- Prior belief, $p_0(D)$ is prevalence.

Updating based on test results:  $p(D | test) = p(test result |D) p_0(+) / (normalization)$
[Demonstration: Process for "inverting" a probability.] -->
:::

::::




------------------------------

## Lesson 29

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 29

1. Explain the permutation test and compare and contrast it with a bootstrap distribution.

2. Generate and interpret visualizations for data with two categorical variables.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 29 Classifiers 4

#. Identify (absolute) risk as a probability.

#. Distinguish between relative and absolute risk and, similarly, between a *difference* in absolute risk between two conditions and the **risk ratio**.

#. Translate probability into odds and log odds, similarly translate a change in risk into an odds ratio.

#. Calculate population attributable fraction and number needed to treat as summaries of risk reduction.

:::

::::



------------------------------

## Lesson 30

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 30

1. Correctly use terminology and notation of hypothesis testing.

2. Using the infer package, conduct a hypothesis test and interpret the results.

3. Compare and contrast confidence intervals and hypothesis tests.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 30 Inference 1

#. Understand "effect size" of a given input variable in terms of a model function: change in model output divided by the change in the given input: a partial derivative.

#. Given a model function, compute effect size for any input. 

#. Observe and understand the origin of sampling variation.

#. Use bootstrapping to create a confidence interval on effect size and interpret confidence interval in terms of sampling variation.
:::

::::



------------------------------

## Lesson 31

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 31

1. Correctly use terminology and notation of interpreting hypothesis tests.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 31 Inference 2

#. Use software to construct a regression table for a linear regression.

#. Correctly interpret the coefficient and standard error columns of a regression table in terms of effect size and sampling variation.

#. Recognize that effect size can depend on the model specification.

#. Give a correct story example of Simpson's paradox and summarize in terms of model specification.

[Demonstration: Vector projection explanation of Simpson's paradox.]
:::

::::



------------------------------

## Lesson 32

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 32

1. Conduct and interpret a hypothesis test for the difference of two means.

2. Calculate and interpret a confidence interval for the difference of two means.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 32 Inference 3

#. Calculate R^2^ for a regression model and correctly interpret it in terms of the "model triangle."

#. Explain why R^2^ will not be zero and may even be close to 1, even when the explanatory variables are unrelated to the response variable. 

#. Given R^2^, $n$, and $p$, calculate the F statistic. 

#. Understand that F near 1 indicates that the explanatory variables are unrelated to the response variable.
:::

::::



------------------------------

## Lesson 33

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 33 

1. Standardize a variable.

2. Find percentile and probabilities for the t distribution; this includes determining the correct degrees of freedom.

3. Use the infer package to conduct a theory-based hypothesis test.

4. Know and verify the assumptions of the two-sample t-test.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 33 Inference 4

1. Identify when one model is nested in another.

2. Use software to construct an ANOVA table and from that construct R^2^ for each nested model described in the table. 

[Note in draft: Use augmented anova table with a leading row for the intercept.]

3. Interpret the F for each row in terms of the increase in R^2^ for that row.
:::

::::



------------------------------

## Lesson 34

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 34

1. Build and interpret a regression table and use correct terminology.

2. Write the hypotheses from the regression table.

3. Use the p-value from a regression table to make a decision about the relationship between the explanatory and response variables.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 34 Inference 5

Using data to update belief.

Operationalize "belief" in terms of effect size.

Framework 1: Bayesian set up for belief function and updating with data. Updated belief is p(effect size | data)

Framework 2: Null hypothesis is that effect size is nil. p-value is p(data | effect size=0)

:::

::::



------------------------------

## Lesson 35

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 35

1. Explain and test the assumptions for inference in a linear regression model.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 35 Inference 6

Calculating p-values in various settings, reading from regression and ANOVA tables.
:::

::::



------------------------------

## Lesson 36

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 36

1. Construct and interpret bootstrap confidence intervals, both percentile and standard error method, for regression parameters such as slope and correlation coefficient.

2. Conduct and interpret a permutation test on the regression slope parameter.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 36 Inference 7

1. Describe factors that can lead to "false discovery."

2. Explain how replication can be used to diagnose false discovery and why this works. 

:::

::::




------------------------------

## Lesson 37

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 37

1. Use the output of a regression table to conduct a hypothesis test and build a confidence interval for the slope parameter from a linear regression model.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 37

Review and catch up.
:::

::::

------------------------------

## Math 300 objectives not touched on in Math 300R

1. a

2. b

------------------------------

## Deleted objectives for 300R

These are objectives that are left out for lack of class time.

1. Graphically interpret a receiver operator curve (ROC) and understand how to compute the location of individual points on the curve.

2. Construct a suitable loss function for a given situation (e.g. HIV testing and blood screening, etc.)

3. Select an optimal decision threshold given an ROC and a loss function.


