project:
  type: website
  output-dir: docs

website:
  title: "Spring 2023 Math 300 Revisions"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Proposal
      - href: lessons.qmd
        text: Lessons
      - href: layout.qmd
        text: Site layout
      - href: objective-list.qmd
        text: Objectives
      - href: LC-list.qmd
        text: LCs
format:
  html:
    theme: cosmo
    css: styles.css



