project:
  type: website
  output-dir: docs

website:
  title: "Proposal for Math 300 Revisions"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: schedule-of-objectives.qmd
        text: Objectives

format:
  html:
    theme: cosmo
    css: styles.css



