project:
  type: website
  output-dir: docs

website:
  title: "Stat-300"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - fall2022.qmd
      - about.qmd
      - outline.qmd

format:
  html:
    theme: cosmo
    css: styles.css



