project:
  type: website
  output-dir: docs

website:
  title: "Spring 2023 Math 300Z"
  navbar:
    title: "Math 300Z"
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: textbooks.qmd
        text: "Textbooks"
      - href: faculty-notes.qmd
        text: "Faculty notes"
      - href: math300-software.qmd
        text: "Software"
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - mathjax-definitions.html



