project:
  type: website
  output-dir: docs

website:
  title: "Spring 2023 Math 300 Revisions"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Proposal
      - href: layout.qmd
        text: Home
      - href: schedule-of-objectives.qmd
        text: Objectives
      - href: NTIs.qmd
        text: NTIs
format:
  html:
    theme: cosmo
    css: styles.css



