---
title: "Fall 2022 Edition"
---

**Explanation** This is an annotated schedule of the Fall 2022 edition of Math 300, the first semester when it's being taught from the *Modern Dive* textbook. The annotations refer to proposed changes for Spring 2023.

This schedule, based on [this Teams file](https://usafa0.sharepoint.com/:x:/r/sites/Math300Fall2022/Class%20Materials/Math%20300%20Syllabus.xlsx?d=wb26cb67a3f254356b054cfa58d6a3814&csf=1&web=1&e=SRO0uw), is current as of Sept 9, 2022. This document will be updated to reflect any re-arrangement of the Math 300 Fall 2022 schedule.

---------

## Block 1: Data, Graphics, and Wrangling

1.	Data with R
    * Reading: MD^[*Modern Dive*] Chapter 1
    * Homework: LC^[Learning check] 1.1 - 1.7	
2.	Scatterplots	
    * Reading: MD §2 - 2.3	
    * Homework: LC 2.1 - 2.8	
3.	Linegraphs, Histograms, and Facets	
    * Reading: MD §2.4 - 2.6	
    * Homework: LC 2.9 -2.21	
4.	Boxplots and Barcharts
    * Reading: §2.7 - 2.9	
    * Homework: LC 2.22 - 2.37	
5.	filter and summarize	
    * Reading: MD §3 - 3.3	
    * Homework: 
        - LC 3.1 - 3.4,	
        - Problem Set 1
6.	group_by, mutate, and arrange	
    * Reading: MD §3.4 - 3.6	
    * Homework LC 3.5 - 3.12	
7.	join, select, rename, and top_n	
    * Reading: MD §3.7 - 3.9	
    * Homework: LC 3.13 - 3.20	
8.	Importing Data	
    * Reading: MD §4 - 4.2	
    * Homework: LC 4.1 - 4.3	
9.	Case Study/ Review	
    * Reading: 4.3 - 4.5	
    * Homework: 
        - LC 4.4 - 4.5
        - Problem Set 2
10.	GR 1 (Chapters 1-4)			

## Block 2: Regression

1.	SLR^[Simple linear regression] - Continuous x	
    - Reading: §5 - 5.1	
    - Homework: LC 5.1 - 5.3	
2.	SLR - Discrete x	
    - Reading: §5.2	
    - Homework: LC 5.4 - 5.7	
3.	SLR - Related Topics	
    - Reading: §5.3 - 5.4	
     Homework: LC 5.8	
4.	Multiple Regression - Numerical & Discrete	
    - Reading: §6 - 6.1	
    - Homework:
        - LC 6.1	
        - Problem Set 3
5.	Multiple Regression - Two Numerical	
    - Reading: §6.2	
    - Homework: LC 6.2 - 6.3	
6.	Multiple Regression - Related Topics	
    - Reading: §6.3		
7.	Multiple Regression Conclusion/Review	
    - Reading: §6.4		
    - Homework: PS 4
8.	GR 2 (Chapters 5-6)			GR 2

## Block 3: Sampling variability and confidence intervals

1. Sampling 	
    - Reading: §7 - 7.2	
    - Homework: LC 7.1 - 7.7	
2. Sampling Framework	
    - Reading: §7.3	
    - Homework: LC 7.8 - 7.20	
3. Case Study	
    - Reading: §7.4	
    - Homework: LC 7.21 - 7.24	
4. CLT, Normal Distribution	
    - Reading: §A.2, 7.5 - 7.6	
    - Homework: LCA.1, LCA.2	
5. Bootstrap Intro	
    - Reading: §8 - 8.2	
    - Homework: 
        - LC 8.1 - 8.2	
        - Problem Set 5
6. Understanding CI	
    - Reading: §8.3	
    - Homework: LC 8.3 - 8.4	
7. Constructing CI	
    - Reading: §8.4	
    - Homework: LC 8.5	
8. Interpreting CI	
    - Reading: §8.5		
9. Case Study	
    - Reading: §8.6		
    - Homework: Problem Set 6
10. GR 3 (Chapters 7-8) GR3

## Block 4: Hypothesis tests

1. Permutation Tests	
    - Reading: §9 - 9.1		
2. Conducting Hypothesis Tests	
    - Reading: §9.2 - 9.3	
    - Homework: LC 9.1 - 9.4	
3. Interpreting Hypothesis Tests	
    - Reading: §9.4	
    - Homework: LC 9.5 - 9.8	
4. Case Study	
    - Reading: §9.5	
    - Homework: LC 9.9 - 9.15	
5. More on Hypothesis Tests	
    - Reading: §9.6		
6. Interpreting Regression Tables	
    - Reading: §10 - 10.2		
    - Homework: Problem Set 7
7. Regression Assumptions	
    - Reading: §10.3	
    - Homework: LC 10.1	
8. Regression Inference via Simulation	
    - Reading: §10.4	
    - Homework: LC 10.2	
9. Summary	
    - Reading: §10.5		
    - Homework: PS 8
10. GR 4 (Chapters 9-10)			GR 4

11. Case Study	
    - Reading: §11 - 11.2	
    - Homework: LC 11.1	
12. Inference Examples	
    - Reading: B (???)		


