---
title: "Layout of this site"
---

This is the proposal/layout site for the Spring 2023 revisions to Math 300, which we're calling "Math 300R" to distinguish it from the Fall 2022 version of the course. The site contains notes and other materials for each of the (revised) lessons in Math 300R.

As of October 2022, the revisions are for lessons 19-37. Revisions, if any, to earlier lessons may be added. Eventually, the revised lessons and the unrevised lessons should be consolidated into a single site. This might occur in December 2022.

There are four main directories. In each directory, the contents are split up on a lesson-by-lesson basis.

- **Objectives**: Student-facing learning goals that make explicit the skills and understandings that students are expected to develop in the course of each lesson. These files are formatted in a specific manner that provides an ID to each objective. Software reads the files so that each objective can be referred to in any document without duplication. That is, the files in this `Objectives` directory are the *source of truth* for the objectives for each of the revised lessons. Any edits or additions to the objectives **must be performed** in the files in this directory.

- **NTI**: Lesson-by-lesson "Notes To Instructors." These are intended to guide instructors through each lesson. They usually contain references to the objectives stored in the `Objectives` directory. In draft form, the NTIs typically contain notes that are to be moved eventually to the "Reading notes."

- **LC**: Like `Objectives`, this directory contains lesson-by-lesson exercises, styled "learning checks" in the style of the *Statistical Inference via Data Science* textbook. Not all the learning checks need to be assigned. Which ones are assigned for each lesson will be noted in the NTIs.

- **Reading-notes**: Textbook-like readings, also organized lesson-by-lesson (as opposed to the chapter organization typically found in textbooks.) Often, several lessons in sequence refer to the same statistical topic. Nonetheless, the reading notes are divided on a lesson basis. It is anticipated that these will be provided to students in an on-line format.
