---
title: "List of learning checks"
---

This list is assembled from the individual-lesson learning check files in the LC/ directory. Make any changes in that directory.

## Lesson 19

```{r child="LC/LC-lesson19.qmd"}
```

## Lesson 20


```{r child="LC/LC-lesson20.qmd"}
```

## Lesson 21


```{r child="LC/LC-lesson21.qmd"}
```

## Lesson 22


```{r child="LC/LC-lesson22.qmd"}
```

## Lesson 23


```{r child="LC/LC-lesson23.qmd"}
```

## Lesson 24


```{r child="LC/LC-lesson24.qmd"}
```

## Lesson 25


```{r child="LC/LC-lesson25.qmd"}
```

## Lesson 26


```{r child="LC/LC-lesson26.qmd"}
```

## Lesson 27

```{r child="LC/LC-lesson27.qmd"}
```

## Lesson 28


```{r child="LC/LC-lesson28.qmd"}
```

## Lesson 29


```{r child="LC/LC-lesson29.qmd"}
```

## Lesson 30


```{r child="LC/LC-lesson30.qmd"}
```

## Lesson 31


```{r child="LC/LC-lesson31.qmd"}
```

## Lesson 32


```{r child="LC/LC-lesson32.qmd"}
```

## Lesson 33


```{r child="LC/LC-lesson33.qmd"}
```

## Lesson 34


```{r child="LC/LC-lesson34.qmd"}
```

## Lesson 35


```{r child="LC/LC-lesson35.qmd"}
```

## Lesson 36


```{r child="LC/LC-lesson36.qmd"}
```

## Lesson 37


```{r child="LC/LC-lesson37.qmd"}
```

## Lesson 38


```{r child="LC/LC-lesson38.qmd"}
```

