---
title: "Math 300R day-by-day Lessons"
---

```{r include=FALSE}
lesson_links <- function(n) {
  str <- "[NTI](NTI/NTI-Lesson{n}.html) : [Objectives](Objectives/Obj-lesson-{n}.html) : [LC](LC-lesson{n}.html) : [Reading](Reading-notes/Reading-notes-lesson-{n}.html)"
  return(glue::glue(str))
}
```
 
 
## Lessons 1-18

See [Fall 2022 repository](https://github.com/DS-USAFA/Core_Stats).

**Data, graphics, wrangling**

1. Data with R
2. Scatterplots
3. Linegraphs, histograms, facets
4. Boxplots and barcharts
5. filter and summarize
6. group_by, mutate, arrange
7. join, select, rename, & top n
8. Importing data
9. Case study/review
10. GR1 (chapters 1-4)

**Regression** 

11. SLR: Continuous x
12. SLR: Discrete x
13. SLR: Related topics
14. Multiple regression: Numerical & discrete
15. Multiple regression: Two numerical
16. Multiple regression: Related topics
17. Multiple regression: Conclusion/review
18. GR 2 (chapters 5-6)

## New lessons

**Variation**

19. Decisions with data `r lesson_links(19)`
20. Reality versus gaming `r lesson_links(20)`
21. DAGs, noise, and simulation `r lesson_links(21)`
22. Sampling variation `r lesson_links(22)`
23. Estimate sampling variation from a single sample `r lesson_links(23)`
24. Effect size `r lesson_links(24)`
25. Mechanics of prediction `r lesson_links(25)`
26. Constructing a prediction interval `r lesson_links(26)`
27. GR 3 (Lessons 19-26) 

**Inference**

28. Covariates `r lesson_links(28)`
29. Covariates eat variance `r lesson_links(29)`
30. Confounding `r lesson_links(30)`
31. Non-causal correlation `r lesson_links(31)`
32. Experiment and random assignment `r lesson_links(32)`
33. Measuring and accumulating risk `r lesson_links(33)`
34. Constructing a classifier `r lesson_links(34)`
35. Accounting for prevalence `r lesson_links(35)`
36. Hypothesis testing `r lesson_links(36)`
37. Calculating a p-value `r lesson_links(37)`
38. False discovery with hypothesis testing `r lesson_links(38)`
39. GR 4 (lessons 28-38) 
40. Review 
