---
title: "Stat 300 objectives vs Stat 300R"
author: "Daniel Kaplan"
date: "As of Sept. 14, 2022"
---

------------------------------

## Lesson 19

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 19
1. Explain the need for randomization in sampling.

2. Explain the impact of sample size on the sample distribution and number of replications on the sampling procedure.

3. Using a sampling distribution, make decisions about the population. In other words, understanding the effect of sampling variation on our estimates.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 19

1. Use and explain the terms accuracy and precision and the technical terms bias and variance. 

2. Carry out (using software) a multiple regression and interpret the coefficients as marginal effects. 

3. Demonstrate sampling variation using sub-sampling on simple and multiple-regression model coefficients.
:::

::::


------------------------------

## Lesson 20

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 20

1. Know and correctly use the terminology and notation for the sampling concepts such as population, census, point estimate, biased, etc.

2. Explain the impact of sample size on the sample distribution and number of replications on the sampling procedure.

3. Use and explain the terms accuracy and precision in the context of sampling.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 20

1. REWRITE: Terminology of covariates, confounders ...

2. Be able to provide an example and explanation of Simpson's paradox.

3. Three
:::

::::



------------------------------

## Lesson 21

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 21

1. Given a sampling scenario, discuss issues such as accuracy and precision as they relate to generalization to the population of interest.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 21

1. Simulating simple DAGs.

2. Construct regression models on simulated data and interpret coefficients as consistent or inconsistent with the generating DAG.

3. Interpret DAGs as a causal hypothesis. 
:::

::::



------------------------------

## Lesson 22

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 22

1. Explain the central limit theorem.

2. For a normal distribution, use `R` to find probabilities and percentiles.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 22 Prediction 1

#. Using software, predict the output that will correspond to an input for a given model. Interpret this in the context of a prediction interval.

#. Graph and interpret the prediction function and prediction confidence bands on low-order linear regression models.


:::

::::



------------------------------

## Lesson 23

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 23

1. Explain the concept of a bootstrap distribution using proper terminology and notation.

2. Use `R` to find the bootstrap distribution of a sample statistic.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 23 Prediction 2

#. Divide prediction confidence bands into a "model uncertainty" component and a "residual" component based on shape and sample size $n$. 

#. Calculate from model residuals the residual component of an (in-sample) prediction error from a regression model.

#. Explain why the mean-square residual and not the mean residual is a suitable measure of the precision (variance) of a prediction from a given model.
:::

::::



------------------------------

## Lesson 24

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 24

1. Explain how to construct a confidence interval using both the percentile method and the standard error method including assumptions. *DK note: Unless you want to emphasize the normal distribution, this is a technical issue and shouldn't be prioritized.

2. Explain how changing the confidence level impacts the width of a confidence interval.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 24 Prediction 3

#. Use provided deterministic models to generate simulated data and add noise of a specified magnitude to the output to produce simulated data containing inputs and outputs.

#. Compare regression results on simulated data to parameters of the simulation (including the amount of noise added to the simulation.) 

#. Show that in-sample prediction error provides a low-biased estimate of added noise.

:::

::::



------------------------------

## Lesson 25

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 25

1. Construct bootstrap percentile and standard error confidence intervals for a single mean or median using the infer package.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 25 Prediction 4

#. Divide data into "training" and "testing" sets.

#. Calculate out-of-sample prediction error. 

#. Observe relationship among sample size $n$, number of parameters $p$, and the calculated in-sample prediction error.

(Note in draft: Later, in hypothesis testing, return to out-of-sample prediction error as analogous to replicating results to establish significance.)
:::

::::



------------------------------

## Lesson 26

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 26

1. Correctly interpret a confidence interval to include identifying incorrect statements.

2. Explain the factors that impact the width of a confidence interval.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 26 Classifiers 1

#. Using software, construct a yes/no classifier based on logistic regression (with a fixed threshold, say 50%). 


#. Cross-tabulate classifier results to calculate true and false positive and negatives. Interpret performance based on "accuracy," "false positive" and "false negative" rates, "sensitivity," and "specificity."

#. Distinguish between probability of true/false given positive and the probability of positive given true/false. Identify which probability type is appropriate for a given purpose.

#. Understand the role of prevalence in shaping probs of true/false given positive and of true/false given negative.

#. Explain why "sensitivity" and "specificity" are independent of prevalence and why this makes them good measures of classifier performance.

#. Construct a suitable loss function for a given situation (e.g. HIV testing and blood screening, etc.)



:::

::::




------------------------------

## Lesson 27

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 27

1. Calculate, using both percentile and standard error methods, confidence intervals for a difference of two proportions.

2. Calculate a normal-based, theory-based, confidence interval for a single proportion or mean.

3. Correctly use all terms and notation to include standard error, margin of error, sampling distribution, and bootstrap distribution.

4. Compare and contrast sampling distribution and bootstrap distribution.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 27 Classifiers 2

1. One 

2. Two

3. Three
:::

::::




------------------------------

## Lesson 28

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 28

No items listed.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 28 Classifiers 3

#. Identify (absolute) risk as a probability.

#. Distinguish between relative and absolute risk and, similarly, between a *difference* in absolute risk between two conditions and the **risk ratio**.

#. Translate probability into odds and log odds, similarly translate a change in risk into an odds ratio.

#. Calculate population attributable fraction and number needed to treat as summaries of risk reduction.


:::

::::




------------------------------

## Lesson 29

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 29

1. Explain the permutation test and compare and contrast it with a bootstrap distribution.

2. Generate and interpret visualizations for data with two categorical variables.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 29 Classifiers 4

A choice between two ways to go:

1. Understand the fundamental logic behind causal attribution.

... or, perhaps more appropriate for the Air Force, ...

1. Graphically interpret a receiver operator curve and understand how to compute the location of individual points on the curve.

2. Select an optimal decision threshold given an ROC and a loss function.

:::

::::



------------------------------

## Lesson 30

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 30

1. Correctly use terminology and notation of hypothesis testing.

2. Using the infer package, conduct a hypothesis test and interpret the results.

3. Compare and contrast confidence intervals and hypothesis tests.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 30 Inference 1

1. One 

2. Two

3. Three
:::

::::



------------------------------

## Lesson 31

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 31

1. Correctly use terminology and notation of interpreting hypothesis tests.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 31 Inference 2

1. One 

2. Two

3. Three
:::

::::



------------------------------

## Lesson 32

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 32

1. Conduct and interpret a hypothesis test for the difference of two means.

2. Calculate and interpret a confidence interval for the difference of two means.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 32 Inference 3

1. One 

2. Two

3. Three
:::

::::



------------------------------

## Lesson 33

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 33 

1. Standardize a variable.

2. Find percentile and probabilities for the t distribution; this includes determining the correct degrees of freedom.

3. Use the infer package to conduct a theory-based hypothesis test.

4. Know and verify the assumptions of the two-sample t-test.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 33 Inference 4

1. One 

2. Two

3. Three
:::

::::



------------------------------

## Lesson 34

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 34

1. Build and interpret a regression table and use correct terminology.

2. Write the hypotheses from the regression table.

3. Use the p-value from a regression table to make a decision about the relationship between the explanatory and response variables.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 34 Inference 5

1. Use software to build regression and ANOVA tables from linear regression.

2. Interpret a regression table in terms of parameters, confidence intervals, and coefficient-wise p-values.

3. Interpret an ANOVA table as a whole-model summary.

4. Use ANOVA for model selection among nested models.
:::

::::



------------------------------

## Lesson 35

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 35

1. Explain and test the assumptions for inference in a linear regression model.

:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 35 Inference 6

1. One 

2. Two

3. Three
:::

::::



------------------------------

## Lesson 36

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 36

1. Construct and interpret bootstrap confidence intervals, both percentile and standard error method, for regression parameters such as slope and correlation coefficient.

2. Conduct and interpret a permutation test on the regression slope parameter.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 36 Inference 7

1. One 

2. Two

3. Three
:::

::::




------------------------------

## Lesson 37

:::: {layout-ncol=2}

::: {.callout-note icon=false}
## Stat 300 Lesson 37

1. Use the output of a regression table to conduct a hypothesis test and build a confidence interval for the slope parameter from a linear regression model.
:::

::: {.callout-tip icon=false}
## Stat 300R Lesson 37

1. One 

2. Two

3. Three
:::

::::





