---
title: "List of objectives"
---

This list is assembled from the individual-lesson files in the Objectives/ directory. Make any changes in that directory.

```{r child="Objectives/Obj-lesson-19.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-20.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-21.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-22.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-23.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-24.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-25.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-26.qmd"}
```

--------

```{r child="Objectives/Obj-lesson-27.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-28.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-29.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-30.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-31.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-32.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-33.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-34.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-35.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-36.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-37.qmd"}
```

--------


```{r child="Objectives/Obj-lesson-38.qmd"}
```

