{
  "hash": "8df8aa8b37861bcc7118582a1ba137a4",
  "result": {
    "markdown": "---\ntitle: \"Math 300R NTI Lesson 19\"\nsubtitle: \"Decisions with data\"\nauthor: \"Prof. Danny Kaplan\"\ndate: \"October 14, 2022\"\noutput:\n  html_document:\n    theme: lumen\n    toc: yes\n    toc_float: yes\n    css: NTI.css\n  pdf_document:\n    toc: yes\n---\n\n\n\n\n## Objectives\n\n\n\n\n\n\n\n\n\n- 19.1 Distinguish between the two settings for decision-making: \n\n    a. **Prediction**: predict an outcome for an individual\n    b. **Relationship**: characterize a relationship with an eye toward intervention or a better understanding of how a mechanism works.\n    \n- 19.2 Given a research question, identify whether it corresponds to a prediction setting or a relationship setting.\n\n\n## Reading\n\nTBD\n\n\n## Lesson\n\n*This lesson marks the beginning of a new phase of the course. Thus far, we've worked with *techniques* for data wrangling, graphics, and regression modeling. Now we address the question of what a regression model (and other information that we might have) can tell us about the real world.*\n\n::: {.callout-tip icon=false}\n## Setup\n\n```r\nlibrary(mosaicData)\n```\n:::\n\n:::: {.callout-note icon=false}\n## Guided activity: House prices\n\n*Have students do the calculations for the first model, answering the questions that follow. After this is complete, have students do the calculations for the second model and answer those questions.*\n\nThe `mosaicData::SaratogaHouses` data frame contains information about the sales price and various attributes of about 1700 houses. (See `?SaratogaHouses` for a detailed description.)\n\nDo a regression of `price ~ bedrooms` and explain what the regression coefficients mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(price ~ bedrooms, data=SaratogaHouses) |> coefficients()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)    bedrooms \n   59862.96    48217.81 \n```\n:::\n:::\n\n\n1. What are the units of the intercept and of the `bedrooms` coefficient? *Intercept in dollars, `bedrooms` in dollars per bedroom.\n\n2. Interpret what the coefficients indicate about the price of houses and bedrooms. *Each additional bedroom adds about $50000 to the value of a house.*\n\n3. According to the model, predict what would be the sales price (at the time the data was collected, 2006) of a house with two bedrooms? *$59863 + 2\\times 48218$*\n\nOf course, bedrooms are not the only important thing about a house. Let's include `livingArea` along with `bedrooms` in the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(price ~ livingArea + bedrooms, data=SaratogaHouses) |> coefficients()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)  livingArea    bedrooms \n  36667.895     125.405  -14196.769 \n```\n:::\n:::\n\n\n1. What are the units of the `livingArea` coefficient? *dollars per square foot*\n2. What does this model say about the value of adding a bedroom? *It seems to reduce the value of the house by about $15,000.*\n\nBased on exactly the same data, the two models seem to give contradictory statements about the value of an additional bedroom. \n\ni. Is one model right and the other wrong? If so, which one is right? (Explain your reasoning.) *Both models are mathematically correct. But they need to be interpreted in different ways. Each is telling us something different about the real world.*\nii. Could both models be right? If so, explain why the `bedroom` coefficients have opposite signs. *We will need to develop some additional tools and concepts before we can take on this question.*\n\nLearning how to interpret models in terms of what they say about the world is a major theme of this second half of Math 300. \n\nAnother, more technical question that we will address has to do with the *precision* of coefficients like 125.40 dollars per square foot. Might it actually be $200/ft^2^? How about $500/ft^2^? And how seriously should we take the sales value that we calculate by setting numbers for `bedrooms` and `livingArea` into the model?\n\n::::\n\n\n\n## Learning Checks\n\n\n\n\n\n\n\n## Setup\n\nThe `math300` package will be needed for lessons 20 through 39.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(math300)\n```\n:::\n\n\n## 19.1 (Objective 2)\n\nWhat are the two settings for decision making that we cover in this course?\n\nGive an example of each.\n\n### Solution\n\n(1) Prediction and (2) Relationship\n\ni. What will be the sales price of this house? *\"This house\" is a shorthand way of saying \"a house with these attributes.\" The sales price will be the output of a prediction function that takes the various attributes as input and produces a sales price as output.*\n\nii. If I look for a house with an additional bathroom, how much will that change the sales price? *This asks for the relationship between number of bathrooms and sales price.*\n\n----------\n\n## 19.2 (Objective 2)\n\nFor each of these research questions, say whether it is a prediction setting or a relationship setting.\n\ni. What's the risk of falling ill? \nii. How will the risk of falling ill change if we eat more broccholi? \niii. Is there any reason to believe, based on the evidence at hand, that we should look more deeply into the possible benefits of broccholi?\n\n\n\n### Solution\n\ni. Prediction\nii. Relationship\niii. Relationship\n\n\n--------\n\n## 19.3\n\nFit a model to some data. Write down the function implied by the coefficients.\n\nEvaluate the function for:\n\ni. a=7, b=9\nii. and so on.\n\n\n### Solution\n\n--------\n\n## 19.4\n\nAbout the summarization of models. Pipe the model fit into any of four functions:\n\ni. `%>% coefficients()`\nii. `%>% broom::tidy()`\niii. `%>% rsquared()`\niv. `%>% confint()`\n\nREDO `confint()` so that the columns are named `lower`, `middle`, `upper`\n\n### Solution\n\n\n--------\n\n\n\n\n\n\n\n## Documenting software\n\n  * File creation date: 2022-10-14\n  * R version 4.2.1 (2022-06-23)\n  * `tidyverse` package version: 1.3.2\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}