---
title: "Math 300R NTI Lesson `r (lesson <- 33)`"
subtitle: "Constructing a classifier"
author: "Prof. Danny Kaplan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    theme: lumen
    toc: yes
    toc_float: yes
    css: NTI.css
  pdf_document:
    toc: yes
---


```{r setup, include=FALSE}
source("../_startup.R")
```


## Objectives

#. Build a classifier from case-control data.

#. Cross-tabulate classifier results versus true state. Evaluate false-positive rate, false-negative rate, accuracy.

#. Calculate different forms of conditional probability: p(A|B) versus p(B|A) and identify which form of conditional probability is useful for prediction of an individual's outcome.


## Reading

TBD


## Lesson

Review the credit-card fraud example. 

::: {.callout-note icon=false}
## Model performance 

Suppose the performance were as presented in the reading

.   | +    |  -
----|------|------
yes | 1900 | 100      
no  |   50 | 3950

Calculate false-positive and false-negative rates from the testing data.

What fraction of fraud was detected?  What fraction of legitimate charges were denied? What's your intuition about whether its worthwhile to have 50 false positives in order to avoid 1900 fraudulent uses?
:::

The testing data was assembled to have a very large fraction of fraudulent events, more than is realistic. What's the *prevalence* of fraud in the testing data?

Suppose that rather than there being 1 fraud for every 2 legitimate charges, there is 1 fraud for every 200 charges. What would be the false-positive and false-negative rates then. 

::: {.callout-important icon=false}
## Class activity

Ask the class to figure this out in small group discussions.
:::





## Learning Challenges



## Documenting software

  

