newwords <- function(str) {
  gsub('`r sds_newword\\("([a-zA-Z \\-]*)"\\)`', "**\\1**", str)
  }

figref <- function(str) {
  gsub('Figure \\\\@ref\\(fig\\:([a-zA-Z0-9\\-]*)\\)', "\\@fig-\\1", str)
  #gsub('Figure \\\\@ref', "\\@fig-", str)
}

test <- r"(It turns out that for either of the causal systems in [Figures @fig-experiment-system or @fig-experiment-pure there is always a correct model to show the link between the intervention and output: Output `r sds_tilde()` Intervention. Rather than modeling the output by the physical quantity X, model the output by the random numbers generated by the computer that were used to set the intervention. This modeling approach is called `r sds_newword("intent to treat")`.)"

fig <- "Figure \\@ref(fig:learn-to-drive-2)"

figref(fig)

newwords(test)

newwords("\"intent to treat\"")
