<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Spring 2023 Math 300 Revisions - Learning Checks Lesson 19</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Spring 2023 Math 300 Revisions</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lessons.html">Lessons</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../layout.html">Site layout</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../objective-list.html">Objectives</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../LC-list.html">LCs</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Learning Checks Lesson 19</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>The <code>math300</code> package will be needed for lessons 20 through 39.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(math300)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(NHANES)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">19.1</h2>
<p>Consider the <code>moderndive::evals</code> data that records students’ evaluations (<code>score</code>, on a 1-5 scale) of the professors in each of several courses (the course <code>ID</code>), as well as the <code>age</code>, “average beauty rating” (<code>bty_avg</code>) of the professor, enrollment in the course (<code>cls_students</code>) and the level o the course (<code>cls_level</code>). Each row in the data frame is an individual course section.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">score</th>
<th style="text-align: right;">age</th>
<th style="text-align: right;">bty_avg</th>
<th style="text-align: right;">cls_students</th>
<th style="text-align: left;">cls_level</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">329</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">2.333</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">upper</td>
</tr>
<tr class="even">
<td style="text-align: right;">313</td>
<td style="text-align: right;">4.2</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">2.667</td>
<td style="text-align: right;">86</td>
<td style="text-align: left;">upper</td>
</tr>
<tr class="odd">
<td style="text-align: right;">430</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">5.833</td>
<td style="text-align: right;">120</td>
<td style="text-align: left;">lower</td>
</tr>
<tr class="even">
<td style="text-align: right;">95</td>
<td style="text-align: right;">4.2</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">4.333</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">upper</td>
</tr>
<tr class="odd">
<td style="text-align: right;">209</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">3.667</td>
<td style="text-align: right;">34</td>
<td style="text-align: left;">upper</td>
</tr>
<tr class="even">
<td style="text-align: right;">442</td>
<td style="text-align: right;">3.6</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">3.333</td>
<td style="text-align: right;">39</td>
<td style="text-align: left;">lower</td>
</tr>
<tr class="odd">
<td style="text-align: right;">351</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">3.333</td>
<td style="text-align: right;">26</td>
<td style="text-align: left;">lower</td>
</tr>
<tr class="even">
<td style="text-align: right;">317</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">6.500</td>
<td style="text-align: right;">44</td>
<td style="text-align: left;">upper</td>
</tr>
<tr class="odd">
<td style="text-align: right;">444</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">4.500</td>
<td style="text-align: right;">111</td>
<td style="text-align: left;">lower</td>
</tr>
<tr class="even">
<td style="text-align: right;">315</td>
<td style="text-align: right;">3.8</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">6.000</td>
<td style="text-align: right;">88</td>
<td style="text-align: left;">upper</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The following commands model <code>score</code> versus <code>age</code> and plots the data as a point plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(score <span class="sc">~</span> age, <span class="at">data =</span> moderndive<span class="sc">::</span>evals) <span class="sc">%&gt;%</span> <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age 
 4.461932354 -0.005938225 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>openintro<span class="sc">::</span>evals <span class="sc">%&gt;%</span> <span class="fu">gf_point</span>(score <span class="sc">~</span> age, <span class="at">alpha=</span><span class="fl">0.2</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="1">
<li>Explain why some of the dots are darker than others?</li>
</ol>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>All the ages have integer values—e.g., 43, 44, 45—so the dots line up in vertical lines.</p>
<p>Similarly, the scores have values only to one decimal place—e.g., 3.1, 3.2, 3.3—so the dots line up in horizontal lines. If there are two or more rows in <code>evals</code> that have the same age and score, the dots will be plotted over one another. Since transparency (<code>alpha = 0.2</code>) is being used, points where there is a lot of overplotting will appear darker.</p>
</div>
</div>
<ol start="2" type="1">
<li>Remake the plot, but using <code>gf_jitter()</code> instead of <code>gf_point()</code>. Explain what’s different about the jittered plot. (Hint: Almost all of the dots are the same lightness.)</li>
</ol>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>openintro<span class="sc">::</span>evals <span class="sc">%&gt;%</span> <span class="fu">gf_jitter</span>(score <span class="sc">~</span> age, <span class="at">alpha=</span><span class="fl">0.2</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>“Jittering” means to shift each dot by a small random amount. This reduces the number of instances where dots are overplotted.</p>
</div>
</div>
<ol start="3" type="1">
<li>Now make a jitter plot of score versus class level (<code>cls_level</code>).
<ol type="a">
<li>What do the tick-mark labels on the horizontal axis describe? Are they numerical?</li>
<li>To judge from the plot, are their more lower-level than upper-level courses? Explain briefly what graphical feature lets you answer this question at a glance.</li>
</ol></li>
</ol>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>openintro<span class="sc">::</span>evals <span class="sc">%&gt;%</span> <span class="fu">gf_jitter</span>(score <span class="sc">~</span> cls_level)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="a">
<li>The tick-mark labels are the levels of the categorical variable <code>cls_level</code>. The are words, not numbers.</li>
<li>There are many more dots in the right column than in the left. Since <code>lower</code> level class are shown in the left column, there are fewer lower-level courses than upper-level courses.</li>
</ol>
</div>
</div>
<ol start="4" type="1">
<li><p>The two columns of points in the plot you made in (3) are not separated by very much empty space. You can fix this by giving <code>gf_jitter()</code> an argument <code>width=0.2</code>. Try different numerical values for <code>width</code> and report which one you find most effective at making the two columns clearly separated while avoiding overplotting.</p></li>
<li><p>Are the scores, on average, different for the lower- vs upper-level classes? It’s hard to get more than a rough idea of the distribution of scores by looking at the “density” of points. The reason is that the number of points differs in the two columns. But there is an easy fix: add a layer to the graphic that shows the distribution (more or less like a histogram displays a distribution of values). You can do this by piping the jitter plot layer into a geom called a “violin,” like this:</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>openintro<span class="sc">::</span>evals <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_jitter</span>(score <span class="sc">~</span> cls_level) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_violin</span>(<span class="at">fill=</span><span class="st">"blue"</span>, <span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">color=</span><span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Explain how to read the violins.</p>
<hr>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1">19.2</h2>
<p>The <code>openintro::promotions</code> data comes the the 1970s and records the gender of 38 people along with the result of a decision to promote (or not) the person. =</p>
<p>Chapter 2 of ModernDive suggests graphically depicting <code>decision</code> versus <code>gender</code> by using a bar plot. There are two ways to make the bar plot, depending on which variable you assign to the horizontal axis and which to the fill color.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>promotions <span class="sc">%&gt;%</span> <span class="fu">gf_bar</span>(<span class="sc">~</span> decision, <span class="at">fill=</span><span class="sc">~</span> gender)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>promotions <span class="sc">%&gt;%</span> <span class="fu">gf_bar</span>(<span class="sc">~</span> gender, <span class="at">fill=</span><span class="sc">~</span>decision)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-promotion-bars-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="LC-lesson19_files/figure-html/fig-promotion-bars-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Two different ways to plot promotion outcome and gender</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-promotion-bars-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="LC-lesson19_files/figure-html/fig-promotion-bars-2.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 2: Two different ways to plot promotion outcome and gender</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Plots like those in <strong>?@fig-promotion-bars</strong> might be attractive or not, depending on your taste. What they don’t accomplish is to make sure which is the response variable and which the explanatory variable.</p>
<p>The choice of response and explanatory variables depends, of course, on what you are trying to display. But everyday English gives a big hint. For instance, you might describe the question at hand as, “Does gender affect promotion decisions.” Here, the variable doing the affecting is <code>gender</code>, and the outcome is the <code>decision</code>.</p>
<p>Modeling decision as a function of gender is easy once you convert the response variable to a zero-one variable. Like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">zero_one</span>(decision, <span class="at">one=</span><span class="st">"promoted"</span>) <span class="sc">~</span> gender, <span class="at">data =</span> promotions)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) genderfemale 
   0.8750000   -0.2916667 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mosaicModel<span class="sc">::</span><span class="fu">mod_eval</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gender model_output
1   male    0.8750000
2 female    0.5833333</code></pre>
</div>
</div>
<ol type="1">
<li>Explain what is the relationship between the model coefficients and the model outputs.</li>
</ol>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The coefficients tell how to calculate the model output. These coefficients say that the model output will be 0.875, but subtract 0.292 if the person is female.</p>
<p>The model outputs give the probability of being promoted for each of the two genders.</p>
</div>
</div>
<ol start="2" type="1">
<li>Make this plot and explain what the red lines show. (We don’t expect you to be able to write the command to generate such plots on your own, but we do expect you to be able to interpret them.)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>promotions <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_jitter</span>(<span class="fu">zero_one</span>(decision) <span class="sc">~</span> gender, <span class="at">height=</span><span class="fl">0.2</span>, <span class="at">width=</span><span class="fl">0.2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_errorbar</span>(model_output <span class="sc">+</span> model_output <span class="sc">~</span> gender, <span class="at">data=</span><span class="fu">mod_eval</span>(mod), </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">color=</span><span class="st">"red"</span>, <span class="at">inherit=</span><span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">label_zero_one</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The red lines show the proportion of the people in each gender group who were promoted. The y-axis scale on the left refers to the zero-one encoding of <code>decision</code>, while the y-axis labels on the right make it easier to read off the numerical value of the proportion.</p>
</div>
</div>
<hr>
</section>
<section id="section-2" class="level2">
<h2 class="anchored" data-anchor-id="section-2">19.3</h2>
<p>The <code>mosaicData::Whickham</code> data from comes from a survey of a thousand or so nurses in the UK in the 1970s. The data record the <code>age</code> of each nurse along with whether the nurse was still alive in a follow-up survey 20 years later (<code>outcome</code>).</p>
<p>Make this graph from the <code>Whickham</code> data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_jitter</span>(<span class="fu">zero_one</span>(outcome) <span class="sc">~</span> age, <span class="at">data =</span> Whickham, <span class="at">alpha=</span><span class="fl">0.3</span>, <span class="at">height=</span><span class="fl">0.1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">label_zero_one</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="1">
<li><p>Explain in everyday language what the graph shows about the lives of humans.</p></li>
<li><p>Make the graph again, but leave out the <code>%&gt;% label_zero_one()</code>. Then explain what <code>label_zero_one()</code> does.</p></li>
</ol>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>The graph shows that young nurses tended to be alive at the 20-year follow-up, older nurses not so much.</p></li>
<li><p><code>%&gt;% label_zero_one()</code> adds an axis on the left of the graph showing that in the zero-one tranform of <code>outcome</code>, “Alive” is assigned the value 1 and “Dead” the value 0.</p></li>
</ol>
</div>
</div>
<section id="solution-6" class="level3">
<h3 class="anchored" data-anchor-id="solution-6">Solution</h3>
<hr>
</section>
</section>
<section id="section-3" class="level2">
<h2 class="anchored" data-anchor-id="section-3">19.4</h2>
<p>About the summarization of models. Pipe the model fit into any of four functions:</p>
<ol type="i">
<li><code>%&gt;% coefficients()</code></li>
<li><code>%&gt;% broom::tidy()</code></li>
<li><code>%&gt;% rsquared()</code></li>
<li><code>%&gt;% confint()</code></li>
</ol>
<p>REDO <code>confint()</code> so that the columns are named <code>lower</code>, <code>middle</code>, <code>upper</code></p>
<section id="solution-7" class="level3">
<h3 class="anchored" data-anchor-id="solution-7">Solution</h3>
<hr>
</section>
</section>
<section id="obj.-19.3" class="level2">
<h2 class="anchored" data-anchor-id="obj.-19.3">19.5 (Obj. 19.3)</h2>
<p>Calculation of a 95% coverage interval (or any other percent level interval) is straightforward with the right software. To illustrate, consider the efficiency of cars and light trucks in terms of CO_2 emissions per mile driven. We’ll use the <code>CO2city</code> variable in the <code>math300::MPG</code> data frame. The basic calculation using the <code>mosaic</code> package is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>( <span class="sc">~</span> CO2city, <span class="at">data =</span> math300<span class="sc">::</span>MPG, <span class="fu">coverage</span>(<span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response   lower   upper
1  CO2city 276.475 684.525</code></pre>
</div>
</div>
<p>The following figure shows a violin plot of <code>CO2city</code> which has been annotated with various coverage intervals. Use the calculation above to identify which of the intervals corresponds to which coverage level.</p>
<ol type="1">
<li>50% coverage interval -A- (c)</li>
<li>75% coverage interval -A- (e)</li>
<li>90% coverage interval -A- (g)</li>
<li>100% coverage interval -A- (i). This extends from the min to the max, so you could have figured this out just from the figure.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/kangaroo-freeze-candy-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="obj-19.3" class="level2">
<h2 class="anchored" data-anchor-id="obj-19.3">19.6 (Obj 19.3)</h2>
<p>The two jitter + violin graphs below show the distribution of two different variables, X and Y. Which variable has more variability?</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/goat-take-linen-1-1.png" class="img-fluid" style="width:50.0%"></p>
</div>
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/goat-take-linen-1-2.png" class="img-fluid" style="width:50.0%"></p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is about the same level of variability in variable A and variable B. This surprises some people. Remember, the amount of variability has to do with the spread of <em>values</em> of the variable. In variable B, those values are have a 95% prediction interval of about 30 to 65, about the same as for variable A. There are two things about plot (b) that suggest to many people that there is more variability in variable B.</p>
<ol type="1">
<li>The larger horizontal spread of the dots. Note that variable B is shown along the vertical axis. The horizontal spread imposed by jittering is completely arbitrary: the only values that count are on the y axis.<br>
</li>
<li>The scalloped, irregular edges of the violin plot.</li>
</ol>
<p>On the other hand, some people look at the clustering of the data points in graph (b) into several discrete values, creating empty spaces in between. To them, this clustering implies less variability. And, in a way, it does. But the <em>statistical</em> meaning of variability has to do with the overall spread of the points, not whether they are restricted to discrete values.</p>
</div>
</div>
<hr>
</section>
<section id="objs.-19.3-19.4" class="level2">
<h2 class="anchored" data-anchor-id="objs.-19.3-19.4">19.7 (Objs. 19.3 &amp; 19.4)</h2>
<p>The graphs below show a violin plot of body mass index (BMI) for adults and children. One of the graphs shows a correct 95% coverage interval on BMI, the other does not.</p>
<p>Identify the incorrect graph and say what feature of the graph led to your answer.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/goat-hurt-painting-1-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="LC-lesson19_files/figure-html/goat-hurt-painting-1-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Graph (b) is correct. In graph (a), you can see that the interval fails to include a lot of the low BMI children and extends too high. For adults, the graph (a) interval extends too far low and doesn’t go high enough.</p>
</div>
</div>
<hr>
</section>
<section id="e" class="level2">
<h2 class="anchored" data-anchor-id="e">19.E</h2>
<p>There are two equivalent formats describing an interval numerically that are widely used:</p>
<ol type="i">
<li>Specify the lower and upper endpoints of the interval, e.g.&nbsp;7 to 13.</li>
<li>Specify the center and half-width of the interval, e.g.&nbsp;10 ± 3, which is just the same as 7 to 13.</li>
</ol>
<p>Complete the following table to show the equivalences between the two notations.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">Interval</th>
<th style="text-align: left;">bottom-to-top</th>
<th style="text-align: left;">plus-or-minus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(a)</td>
<td style="text-align: left;">3 to 11</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">(b)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">108 ± 10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(c)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">30 ± 1</td>
</tr>
<tr class="even">
<td style="text-align: left;">(d)</td>
<td style="text-align: left;">97 to 100</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">(e)</td>
<td style="text-align: left;">-4 to 16</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="a">
<li>7 ± 4</li>
<li>98 to 118</li>
<li>29 to 31</li>
<li>98.5 ± 1.5</li>
<li>6 ± 10</li>
</ol>
<p>It’s a matter of judgement which format to use. The bottom-to-top notation highlights the range of the interval while the plus-or-minus notation emphasizes the center of the interval. As a rule of thumb, I suggest this:</p>
<ul>
<li>If the first two digits are different between the top and bottom of the interval, use the bottom-to-top notation. So, write 387 to 393. If the first two digits are the same, use plus-or-minus. For instancer, the ratio of the mass of the Earth to that of the Moon is 81.3005678 ± 0.0000027. This is easier to take in at a glance than the equivalent 81.3005651 - 81.3005708</li>
</ul>
</div>
</div>
<hr>
</section>
<section id="f" class="level2">
<h2 class="anchored" data-anchor-id="f">19.F</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>