<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Danny Kaplan">
<meta name="dcterms.date" content="2022-11-16">

<title>Lessons in Statistical Thinking - 5&nbsp; Estimating sampling variation from a single sample</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Reading-notes-lesson-24.html" rel="next">
<link href="./Reading-notes-lesson-22.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimating sampling variation from a single sample</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Lessons in Statistical Thinking</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preliminaries</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-19.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical thinking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-20.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Measuring and simulating variation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-21.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Signal and noise</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-22.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling variation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-23.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimating sampling variation from a single sample</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-24.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Effect size</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#subsampling" id="toc-subsampling" class="nav-link active" data-scroll-target="#subsampling"> <span class="header-section-number">5.1</span> Subsampling</a></li>
  <li><a href="#bootstrapping" id="toc-bootstrapping" class="nav-link" data-scroll-target="#bootstrapping"> <span class="header-section-number">5.2</span> Bootstrapping</a></li>
  <li><a href="#using-the-residuals" id="toc-using-the-residuals" class="nav-link" data-scroll-target="#using-the-residuals"> <span class="header-section-number">5.3</span> Using the residuals</a></li>
  <li><a href="#margin-of-error" id="toc-margin-of-error" class="nav-link" data-scroll-target="#margin-of-error"> <span class="header-section-number">5.4</span> Margin of error</a></li>
  <li><a href="#tiny-n-optional" id="toc-tiny-n-optional" class="nav-link" data-scroll-target="#tiny-n-optional"> <span class="header-section-number">5.5</span> Tiny <span class="math inline">\(n\)</span> (optional)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimating sampling variation from a single sample</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Danny Kaplan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 16, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>Lesson 21 introduced the idea of separating data into separate components: signal and noise. The <em>signal</em> is a summary of the data that tells us something we want to know. Often, the signal will be one or more coefficients from a regression report, but it might be something as simple as the mean or median or standard deviation of a variable in a data frame.</p>
<p>The <em>noise</em> comes into the data from any of a variety of sources: e.g.&nbsp;error in measurement or a data-entry blunder. Another source of noise is omnipresent (except in a perfect census): sampling variation. The idea behind sampling variation is that the particular data at hand is just one sample and is contingent on the time and situation in which the data were collected. Data collection at a different time or situation would presumably be somewhat different.</p>
<p>The Greek philosopher Heraclitus (c.&nbsp;500 BC) said, “You can’t step into the same river twice.” Each time you step into a river, you might be at the same place on the bank but the water around you will be different. A data sample is like collecting water from a river or lake using a dipper. Imagine ten people standing side by side on the shore of a lake, each person dipping into the water acquire a specimen and making one or more measurements from the specimen, for instance the temperature, pH, and bacteria count. Each person collects a sample—that is, a series of specimens. These might be taken one right after the other or by some protocol, say a weekly tracking of lake conditions over time.</p>
<p>The ten people are each doing the same thing in approximately the same place and same time, but each person’s sample—say the collection of 52 weekly specimens over the course of a year—will be different. Perhaps only a little bit different. That sample-to-sample variation will be noise.</p>
<p>If the ten people were fishing, each specimen would be the result of one cast of the rod. Typically this is just an empty hook, lake weeds, or a stick, but sometimes it will be a fish. At the end of the fishing day, each fisherman will have a sample. With fishing luck (or skill), some of the specimens in the sample will be fish. Presumably, the luck (or skill) of the fishermen will differ one from the other. That’s the noise of sampling variation. To fishermen the question of interest, the signal they want to measure, might be, “How good is the fishing today?” Each answers that question by looking at how many fish he or she caught. The ten fishermen’s catch will differ: sampling variation. Consequently, each fisherman’s answer will be contaminated with some noise. The fisherman’s summary (the count of fish caught) will have some noise stemming from sampling variation.</p>
<p>In Lesson 21, to gain some feeling for sampling variation, we repeated trials over and over gain. Each trial consisted of collecting a sample (that is, multiple specimens) and summarizing it. The individual trial is a summary of a sample. We then summarized the whole set of trials with the standard deviation. This is how we quantified sampling variation.</p>
<p>Now it is time to take off the DAG training wheels and measure sampling variation from actual data, from a <em>single</em> sample. This sounds like an impossible task. Sampling variation is about the variation in summaries <em>between</em> samples. With a <em>single</em> sample there is no “between” to be had.</p>
<p>What we will need to estimate sampling variation from a <em>single</em> sample is a way to simulate drawing new samples from the single sample.</p>
<section id="subsampling" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="subsampling"><span class="header-section-number">5.1</span> Subsampling</h2>
<p>Authors of statistics books tend to choose examples based on their own interests rather than their students’, so in this section let’s look at athletic performance as people age. The <code>TenMileRace</code> data are readily to hand, so we’ll look at net race time (from start line to finish line) as a function of age. We’ll limit the study to people over 40.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>TenMileRace <span class="sc">%&gt;%</span> <span class="fu">filter</span>(age <span class="sc">&gt;</span> <span class="dv">40</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(net <span class="sc">~</span> age, <span class="at">data =</span> .) <span class="sc">%&gt;%</span> <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 4278.21279    28.13517 </code></pre>
</div>
</div>
<p>The units of <code>net</code> are seconds, the units of <code>age</code> are years (as conventional). The model coefficient on <code>age</code> tells us how the <code>net</code> time changes for each additional year of <code>age</code>. This summary of the data tells us that the time to run the race gets longer by about 28 seconds per year. So a 45-year-old runner who completed this year’s 10-mile race in 3900 seconds (that’s about 9.2 mph, a pretty good pace!) might expect that, in ten years, when she is 55 years old her time will be longer by 280 seconds.</p>
<p>It would be asinine to report the ten-year change as 281.3517 seconds. The runner’s time ten years from now will be influenced by the weather, crowding, the course conditions, whether she finds a good pace runner, the training regime, improvements in shoe technology, injuries, illnesses, etc. There’s little or nothing we can say from the <code>TenMileRace</code> data about such factors.</p>
<p>But we should not forget sampling variation. <code>TenMileRace</code> has 2898 includes 2898. The way the data was collected (radio-frequency interogation of a dongle on the runner’s shoe) suggests that the data is a census of finishers, but really it is a sample of the kind of people who run such races. People might have been interested in running but had a schedule conflict, or lived too far away, or missed their train into the start line in the city. So we’ll treat the data as a sample.</p>
<p>This sample of 2898 runners is the only sample we have, so there is no option to compare multiple samples in order to look at sampling variation. That’s no excuse for not making an interval estimate on the <code>age</code> coefficient. We have to use some ingenuity.</p>
<p>Here’s an idea. Instead of using samples of size 2898, let’s use sub-samples one-tenth the size: <span class="math inline">\(n=290\)</span>. We’ll select the subsamples at random:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Over40 <span class="ot">&lt;-</span> TenMileRace <span class="sc">%&gt;%</span> <span class="fu">filter</span>(age <span class="sc">&gt;</span> <span class="dv">40</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(time <span class="sc">~</span> age, <span class="at">data =</span> Over40 <span class="sc">%&gt;%</span> <span class="fu">sample</span>(<span class="at">size=</span><span class="dv">290</span>)) <span class="sc">%&gt;%</span> <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 4694.73528    23.37827 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(time <span class="sc">~</span> age, <span class="at">data =</span> Over40 <span class="sc">%&gt;%</span> <span class="fu">sample</span>(<span class="at">size=</span><span class="dv">290</span>)) <span class="sc">%&gt;%</span> <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 4669.07546    23.89813 </code></pre>
</div>
</div>
<p>The age coefficients differ one from the other by about 0.5 seconds. Better, let’s select many subsamples of size 1449 at random, and find the age coefficient for each of them. We will run 100 trials</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a sample of summaries</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Trials <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> {</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(time <span class="sc">~</span> age, <span class="at">data =</span> <span class="fu">sample</span>(Over40, <span class="at">size=</span><span class="dv">290</span>)) <span class="sc">%&gt;%</span> <span class="fu">coefficients</span>()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># a summary of the sample of summaries</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>Trials <span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">se =</span> <span class="fu">sd</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        se
1 9.042024</code></pre>
</div>
</div>
<p>We used the name <code>se</code> for the summary of samples of summaries because what we have calculated is the standard error of the age coefficient in a sample of size <span class="math inline">\(n=290\)</span>.</p>
<p>In Lesson 22 we saw that the standard error is proportional to <span class="math inline">\(1/\sqrt{\strut n}\)</span>, where <span class="math inline">\(n\)</span> is the sample size. From the subsamples, know that the SE for <span class="math inline">\(n=290\)</span> is about 9.0 seconds. This tells us that the SE for the full <span class="math inline">\(n=2898\)</span> samples would be about <span class="math inline">\(9.0 \frac{\sqrt{290}}{\sqrt{2898}} = 2.85\)</span>.</p>
<p>So the interval summary of the <code>age</code> coefficient—the so-called “confidence interval” is <span class="math display">\[\underbrace{28.1}_\text{age coef.} \pm 2\times\!\!\!\!\!\!\! \underbrace{2.85}_\text{standard error} =\ \ \ \  28.1 \pm\!\!\!\!\!\!\!\! \underbrace{5.6}_\text{margin of error}\ \  \text{or, equivalently, 22.6 to 33.6}\]</span></p>
</section>
<section id="bootstrapping" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="bootstrapping"><span class="header-section-number">5.2</span> Bootstrapping</h2>
<!--In the previous section we estimated the standard error of a model coefficient by drawing many smaller samples, running many trials of the smaller samples ($n=1449$), and summarizing them to get the standard error across all the trials: 3.2 seconds. Then we used the theory that the standard error is proportional to $1/\sqrt{n}$ to scale the 3.2 to be appropriate for the full sample size of $n=2898$. -->
<p>There is a trick to generating a random subsample of a data frame with the same <span class="math inline">\(n\)</span> as the data frame: draw the subsample from the original sample <strong>with replacement</strong>. An example will suffice to show what the “with replacement” does:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>example <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># without replacement</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(example)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 4 3 5 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># now, with replacement</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(example, <span class="at">replace=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 4 3 3 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(example, <span class="at">replace=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3 5 4 4 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(example, <span class="at">replace=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 1 2 2 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(example, <span class="at">replace=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4 3 1 4 5</code></pre>
</div>
</div>
<p>The “with replacement” leads to the possibility that some of the values will appear two or more times in the subsample and others of the values will be left out.</p>
<p>The calculation of the SE using sampling with replacement looks like this: <code>r</code>set.seed(207)`</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run many trials</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>Trials <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> {</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(time <span class="sc">~</span> age, <span class="at">data =</span> <span class="fu">sample</span>(Over40, <span class="at">replace=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">coefficients</span>()</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># summarize the trials to find the SE</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>Trials <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">se =</span> <span class="fu">sd</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        se
1 2.948786</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or let the computer do the work of converting to a confidence interval</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>Trials <span class="sc">%&gt;%</span> <span class="fu">confint</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  name    lower   upper level     method estimate
1  age 21.58031 33.3163  0.95 percentile  27.2782</code></pre>
</div>
</div>
<p>This method is called “<strong>bootstrapping</strong> a confidence interval.” The same word, “bootstrapping” is used to describe how a computer turns itself on. It comes from the idea of a <a href="https://en.wikipedia.org/wiki/Bootstrapping">person raising herself from the ground</a> by pulling upward on her own boots. An impossible task. And a suitable metaphor for generating many samples from a single sample.</p>
</section>
<section id="using-the-residuals" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="using-the-residuals"><span class="header-section-number">5.3</span> Using the residuals</h2>
<p>Lesson 21 pointed to the idea of data consisting of two parts: signal plus noise. In Lesson 22 and thusfar in this lesson, we’ve tried to estimate the signal by summarizing the data. But we still had to account for sampling variation, which we did by generating many subsamples.</p>
<p>Another route to measuring sampling variation takes more literally the division of data into signal and noise. The idea is still to estimate the signal by a regression model summary. But now, we take the <strong>residuals</strong> from the model as the evidence for how much noise there is. We quantify the variation in the residuals in the same way that we have always done: their standard deviation. This quantity, the standard deviation of the residuals from a model, has its own technical name: the “residual standard error.” For some types of models, it’s possible to push the residual standard error through the model-fitting apparatus in order to construct standard errors and confidence intervals. The mathematics of this is a matter for specialists, but computers handle the calculations well.</p>
<p>The <code>confint()</code> function knows how to take <code>lm()</code>-fitted models and translate the residuals into confidence intervals. Like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(time <span class="sc">~</span> age, <span class="at">data =</span> Over40) <span class="sc">%&gt;%</span> <span class="fu">confint</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %     97.5 %
(Intercept) 4239.50891 4804.89396
age           21.58833   32.96807</code></pre>
</div>
</div>
<p>Contemporary statistics uses many different model types depending on the situation. In this course we will only use two: linear models and generalized linear models. The field of machine learning has introduced many other kinds of models, often with evocative names like “regression trees,” “random forests,” and “vector support machines.” Usually there is not a way to push the residual standard error through such calculations. But when a confidence interval is needed, the boostrapping method can always be used.</p>
</section>
<section id="margin-of-error" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="margin-of-error"><span class="header-section-number">5.4</span> Margin of error</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>one_trial <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">n=</span><span class="dv">2</span>) {</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  vals <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">m =</span> <span class="fu">mean</span>(vals), <span class="at">s =</span> <span class="fu">sd</span>(vals))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The confidence interval from each trial will be <span class="math inline">\(m \pm \beta s\)</span>, where <span class="math inline">\(\beta\)</span> is a number yet to be determined. How to do so, we want to select <span class="math inline">\(\beta\)</span> so that, across all trials, 95% will include the mean of the distribution from which the data values were drawn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># vary beta until 95% of the trials have a left value smaller than zero.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fl">0.02</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>Trials <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> <span class="fu">one_trial</span>(<span class="at">n=</span>n) <span class="sc">%&gt;%</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">left =</span> m <span class="sc">-</span> beta<span class="sc">*</span>s, <span class="at">right =</span> m <span class="sc">+</span> beta<span class="sc">*</span>s) </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>Trials <span class="sc">%&gt;%</span> </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">coverage =</span> <span class="fu">sum</span>(<span class="fu">sign</span>(left<span class="sc">*</span>right) <span class="sc">&lt;</span> <span class="dv">0</span>)<span class="sc">/</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  coverage
     &lt;dbl&gt;
1    0.967</code></pre>
</div>
</div>
<p>For sample size <span class="math inline">\(n=10\)</span>, <span class="math inline">\(\beta\)</span> needs to be 0.72, while for a sample size <span class="math inline">\(n=100\)</span>, <span class="math inline">\(\beta\)</span> needs to be 0.20. For <span class="math inline">\(n=1000\)</span>, the multiplier needs to be 0.062, and so on. For <span class="math inline">\(n=10000\)</span>, the multiplier needs to be 0.02</p>
<table class="table">
<thead>
<tr class="header">
<th>n</th>
<th><span class="math inline">\(\beta\)</span></th>
<th><span class="math inline">\(t = \beta / \sqrt{\strut n}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10</td>
<td>0.72</td>
<td>2.26</td>
</tr>
<tr class="even">
<td>15</td>
<td>0.55</td>
<td>2.14</td>
</tr>
<tr class="odd">
<td>20</td>
<td>0.47</td>
<td>2.09</td>
</tr>
<tr class="even">
<td>50</td>
<td>0.28</td>
<td>2.01</td>
</tr>
<tr class="odd">
<td>100</td>
<td>0.20</td>
<td>1.98</td>
</tr>
<tr class="even">
<td>500</td>
<td>0.088</td>
<td>1.96</td>
</tr>
<tr class="odd">
<td>1000</td>
<td>0.062</td>
<td>1.96</td>
</tr>
<tr class="even">
<td>10000</td>
<td>0.20</td>
<td>1.96</td>
</tr>
</tbody>
</table>
<p>Notice that as <span class="math inline">\(n\)</span> gets bigger, the size of <span class="math inline">\(\beta\)</span> to cover 95% of the trials gets smaller. More than a century ago, it was known that the multiplier for any sample size <span class="math inline">\(n\)</span> is effectively <span class="math inline">\(2/\sqrt{n}\)</span>. Consequently, the confidence interval for the mean of <span class="math inline">\(n\)</span> values is approximately</p>
<p><span class="math display">\[\mathtt{CI} = \mathtt{mean(x)}\pm \underbrace{\frac{2}{\sqrt{n}} \mathtt{sd(x)}}_\text{margin of error}\]</span></p>
<p>The quantity following the <span class="math inline">\(\pm\)</span> is called the “<strong>margin of error</strong>.” Because of the <span class="math inline">\(\pm\)</span>, he overall length of the confidence interval is twice the margin of error.</p>
<p>It’s much easier to remember <span class="math inline">\(2/\sqrt{n}\)</span> than a list of <span class="math inline">\(\beta\)</span> values that change from one <span class="math inline">\(n\)</span> to the next. Another ubiquitous memory aid involves another technical term, the <strong>standard error</strong>. This involves a simple re-arrangement of the equation for the confidence interval:</p>
<p><span class="math display">\[\mathtt{CI} = \mathtt{mean(x)}\pm 2\underbrace{\frac{\mathtt{sd(x)}}{\sqrt{n}}} _\text{standard error}\]</span></p>
<p>It’s standard in statistical software to report the standard error of a coefficient. Usually abbreviated <code>se</code> or <code>std.error</code> or something similar. The software is doing the divide-by-<span class="math inline">\(\sqrt{n}\)</span> for you, so all you need to construct the margin of error is multiply the standard error by 2. That’s convenient, but it comes at the cost of yet another use of the words “standard” and “error,” which can be confusing.</p>
<p>Here’s an example of a typical software output summarizing a model in the format called a “<strong>regression report</strong>.” Here’s an example, looking at the fuel economy of cars (<code>mpg</code>) as a function the car’s weight (<code>wt</code>) and horsepower (<code>hp</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp, <span class="at">data =</span> mtcars) <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">regression_summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)  37.2      1.60        23.3  2.57e-20
2 wt           -3.88     0.633       -6.13 1.12e- 6
3 hp           -0.0318   0.00903     -3.52 1.45e- 3</code></pre>
</div>
</div>
<p>According to this report, each additional 1000 lbs of weight decreases fuel economy by an estimated 3.9 miles per gallon. But since the model is based on a sample of data, it’s important to report the <em>precision</em> of that number in the face of sampling variation. The confidence interval is the standard format for that precision. It will be the estimate plus-or-minus two times the standard error, that is: <span class="math inline">\(-3.88 \pm 2\times0.633\)</span>, that is, -5.15 to -2.61 mpg per 1000 lbs. Similarly, each addition horsepower (<code>hp</code>) lowers fuel economy by <span class="math inline">\(-0.032 \pm 2 \times 0.009\)</span>, that is, -0.05 to 0.013 mpg per horsepower.</p>
<p>Even more convenient is to calculate the confidence interval with <code>confint()</code> which handles all the computations, including the ones for tiny <span class="math inline">\(n\)</span> described in <span class="quarto-unresolved-ref">?sec-tiny-n</span>.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
How many digits?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notice that the estimate of the <code>wt</code> coefficient in the above regression report is -3.87783074. That seems like an awful lot of digits to report when the confidence interval is -5.15 to -2.61. Or, rather, an awful lot of digits for the human reader.</p>
<p>It is of course easy for the human to ignore the last several digits of the number. This makes reading more reliable; there are not as many digits to confuse. Even worse, the many digits suggest a level of precision that is belied by the width of the confidence interval. (When the number is going to be part of a continuing computation, that is, the “reader” is a computer, mis-interpretion or faulty reading is not an issue, which is why the software calculates so many digits .)</p>
<p>So how many digits ought to be reported for a human reader? There is an easy procedure to determine this.</p>
<ol type="1">
<li><p>Look at the <em>standard error</em> in the regression report and multiply by 2 to get the <strong>margin</strong> of error. For example, for the <code>hp</code> coefficient, the margin of error is <span class="math inline">\(2 \times 0.63273349 = 1.265467\)</span>.</p></li>
<li><p>It is always the case that no more than two digits of the margin of error have any meaning. (Even the second digit would suffer sampling variation.) So round the margin of error to two digits, that is 1.3 for the <code>hp</code> standard error.</p></li>
<li><p>Notice the location of the second digit of the rounded standard error. For <code>hp</code>, the second digit is 3 and it’s located in the one-tenths place. Round the coefficient to this place. So, the <code>hp</code> coefficient -3.87783074 will round to -3.9.</p></li>
<li><p>The confidence interval, formatted for the human reader, will be the rounded coefficient plus-or-minus the rounded standard error. For <code>hp</code>, the confidence interval will be <span class="math inline">\(-3.9 \pm 1.3\)</span> or -5.2 to -2.6.</p></li>
</ol>
</div>
</div>
</section>
<section id="tiny-n-optional" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="tiny-n-optional"><span class="header-section-number">5.5</span> Tiny <span class="math inline">\(n\)</span> (optional)</h2>
<p>When you have a very small sample size—say, <span class="math inline">\(n=2\)</span>—the values may coincidentally be very close together. Around 1907, William Gosset, a scientist at Guinness, discovered that such coincidences force <span class="math inline">\(\beta\)</span> to be much larger than <span class="math inline">\(2/\sqrt{n}\)</span> in order to produce confidence intervals that cover the mean of the data-generating process. Gosset’s particular interest was in making sense of Guinness’s standard testing protocols, which involve averaging the results from three small batches of beer ingredients. Contacting the leading statisticians of the day, Gosset was told that such small <span class="math inline">\(n\)</span> is “brewing, not statistics.” Nonetheless, Gosset had to work within Guinness’s testing protocols, which were indeed brewing but still needed statistical interpretation.</p>
<p>Gosset carried out trials by hand, a large number of measurements from a study of criminals’ hand sizes. (They did this kind of thing in 1900.) Each measurement was written on a card. A trial consisted of drawing <span class="math inline">\(n\)</span> cards from the deck and calculating the mean and standard deviation of the measurements. Using computers, we can simulate the calculation of results from a Gosset-like trials using a simple function that calculates the mean and standard deviation of data from a Gaussian distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>one_trial <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">n=</span><span class="dv">2</span>) {</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  vals <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">m =</span> <span class="fu">mean</span>(vals), <span class="at">s =</span> <span class="fu">sd</span>(vals))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can pick a small <span class="math inline">\(n\)</span> and running many trials using a candidate value for “twice.”</p>
<p>::: {.callout-warning} ## IN DRAFT</p>
<p>CONVERT the <code>beta</code> to something named <code>twice</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">=</span><span class="dv">10</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>Trials <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100</span>) <span class="sc">*</span> <span class="fu">one_trial</span>(<span class="at">n=</span>n) <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">left =</span> m <span class="sc">-</span> beta<span class="sc">*</span>s, <span class="at">right =</span> m <span class="sc">+</span> beta<span class="sc">*</span>s) </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_errorbarh</span>(.index <span class="sc">~</span> left <span class="sc">+</span> right, <span class="at">data =</span> Trials, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_errorbarh</span>(.index <span class="sc">~</span> left <span class="sc">+</span> right, </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> Trials <span class="sc">%&gt;%</span> <span class="fu">filter</span>(left <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">|</span> right <span class="sc">&lt;</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="at">color=</span><span class="st">"blue"</span>, <span class="at">inherit=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Reading-notes-lesson-23_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Gosset effectively tabulated the <span class="math inline">\(\beta\)</span> multipliers</p>
<table class="table">
<thead>
<tr class="header">
<th>n</th>
<th><span class="math inline">\(\beta\)</span></th>
<th><span class="math inline">\(t = \beta / \sqrt{\strut n}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>8.98</td>
<td>12.7</td>
</tr>
<tr class="even">
<td>3</td>
<td>2.48</td>
<td>4.30</td>
</tr>
<tr class="odd">
<td>4</td>
<td>1.59</td>
<td>3.18</td>
</tr>
<tr class="even">
<td>5</td>
<td>1.24</td>
<td>2.78</td>
</tr>
<tr class="odd">
<td>6</td>
<td>1.04</td>
<td>2.57</td>
</tr>
<tr class="even">
<td>7</td>
<td>0.92</td>
<td>2.44</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td>0.72</td>
<td>2.26</td>
</tr>
<tr class="odd">
<td>15</td>
<td>0.55</td>
<td>2.14</td>
</tr>
<tr class="even">
<td>20</td>
<td>0.47</td>
<td>2.09</td>
</tr>
<tr class="odd">
<td>50</td>
<td>0.28</td>
<td>2.01</td>
</tr>
<tr class="even">
<td>100</td>
<td>0.20</td>
<td>1.98</td>
</tr>
<tr class="odd">
<td>500</td>
<td>0.088</td>
<td>1.96</td>
</tr>
<tr class="even">
<td>1000</td>
<td>0.062</td>
<td>1.96</td>
</tr>
</tbody>
</table>
<p>You can see that for <span class="math inline">\(n\)</span> bigger than 10 or 20, the <span class="math inline">\(t\)</span> multiplier is 2. But for very small <span class="math inline">\(n\)</span>, the t-multiplier can be considerably larger.</p>
<p>You can see the wisdom of brewers here. They made tests by averaging measurements from three small batches of beer. If they had used only two batches, the confidence interval would be almost three times larger than for <span class="math inline">\(n=3\)</span>, making it very hard to conclude anything about whether the tests show the ingredients to be within the quality-control standards.</p>
<p>Gosset’s work was published under the pseudonym “Student,” since Guinness forbade employees to publish under their own names. Statisticians, recognizing the value of the work (and knowing the name behind the pseudonym), came to use the name <span class="math inline">\(t\)</span>, perhaps because tea was considered more refined than “beer.” In many statistics texts, you will see the phrase “Student t” to refer to how Gosset’s work is used.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Reading-notes-lesson-22.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling variation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Reading-notes-lesson-24.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Effect size</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>