<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lessons in Statistical Thinking - 17&nbsp; Accounting for prevalence</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Reading-notes-lesson-36.html" rel="next">
<link href="./Reading-notes-lesson-34.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Accounting for prevalence</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Lessons in Statistical Thinking</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-19.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preliminaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-20.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Measuring variation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-21.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Signal and noise</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-22.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling and sampling variation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-23.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimating sampling variation from a single sample</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-24.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Effect size: Input to output</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-25.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Mechanics of prediction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-26.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Constructing a prediction interval</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./QR1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Review of Lessons 1-8</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-28.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Covariates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-29.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Covariates eat variance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-30.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confounding</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-31.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Non-causal correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-32.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Experiment and random assignment</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-33.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Measuring and accumulating risk</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-34.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Constructing a classifier</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-35.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Accounting for prevalence</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-36.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-37.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Calculating a p-value</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-38.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">False discovery</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./QR2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Review of Lessons 9-19</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#prevalence-in-the-population" id="toc-prevalence-in-the-population" class="nav-link active" data-scroll-target="#prevalence-in-the-population"><span class="toc-section-number">17.1</span>  Prevalence in the population</a></li>
  <li><a href="#for-the-patient-with-a-test-result" id="toc-for-the-patient-with-a-test-result" class="nav-link" data-scroll-target="#for-the-patient-with-a-test-result"><span class="toc-section-number">17.2</span>  For the patient with a + test result</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Accounting for prevalence</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Lesson 34 introduced classifiers, model functions where the output is one of two values which we called + and -.</p>
<p>The designer of the classifier chooses what inputs to use and the architecture of the model. The model is fit to training data, thereby producing a specific classifier function.</p>
<p>::: {.callout-note} ## Example: Survival</p>
<p>To illustrate the construction of a classifier function, imagine yourself participating in the 1970s-1990s Whickham study of nurses in the UK. Your task in 1991 is to follow up on more of the nurses who were interviewed in the 1970s. You have already done some of the work and stored the results in the <code>Whickham</code>. To make your search for the remaining nurses more productive, you want to build a classifier whose output, + or -, will direct you to look first in the death records or, for those with a - output, in the employment and pension records.</p>
<p>The inputs to the classifier will be the data you have already assembled: the <code>age</code> and <code>smoker</code> status of the nurse when first interviewed. Since <code>Whickham</code> includes an <code>outcome</code> variable—you’ve already followed up on those nurses—you can train your classifer with that data frame. You have decided on the model <code>outcome ~ age*smoker</code>, but since <code>outcome</code> is categorical with levels <code>"Alive"</code> and <code>"Dead"</code>, you will use a zero-one encoding.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Whickham_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">zero_one</span>(outcome, <span class="at">one=</span><span class="st">"Alive"</span>) <span class="sc">~</span> age<span class="sc">*</span>smoker, <span class="at">data=</span>Whickham)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Whickham_function <span class="ot">&lt;-</span> <span class="fu">makeFun</span>(Whickham_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To get a sense for the range of outputs of the model, you try out the model function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Whickham_function</span>(<span class="at">age =</span> <span class="dv">75</span>, <span class="at">smoker=</span><span class="st">"Yes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.3113829 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Whickham_function</span>(<span class="at">age =</span> <span class="dv">20</span>, <span class="at">smoker=</span><span class="st">"No"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
1.169333 </code></pre>
</div>
</div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Move to Learning Checks: LC 35.H
</div>
</div>
<div class="callout-body-container callout-body">
<p>Explain how come the output of <code>Whickham_function()</code> can be bigger than one?</p>
<p>Use logistic regression to produce a model whose output can be interpreted directly as the probability of being alive at follow up.</p>
</div>
</div>
<p>You are not quite done with the task of building a classifier. The final step is to choose a threshold to translate the numerical output of <code>Whickham_function()</code> into one of the classifer outputs, + or -.</p>
<p>Probably you are not sure what that threshold should be. A good step in such situations is to take a guess and see what you get by way of model performance. Then you can improve the guess if need be. In the following demonstration, we write an R function that takes the <code>age</code> and <code>smoker</code> inputs, uses <code>Whickham_function()</code> to translate them into a number, and applies a threshold to that number to translate it into a + or - output.</p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Demonstration: Turning a model function into a classifier function
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Whickham_classifier <span class="ot">&lt;-</span> <span class="cf">function</span>(age, smoker, threshold) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  number <span class="ot">&lt;-</span> <span class="fu">Whickham_function</span>(<span class="at">age=</span>age, <span class="at">smoker=</span>smoker)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(number <span class="sc">&gt;=</span> threshold, <span class="st">"+"</span>, <span class="st">"-"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Try it out to make sure that the <code>Whickham_classifier()</code> takes appropriate inputs and returns an output in the right form. We’ll use a threshold of 0.6—just a guess.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Examples <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">c</span>(<span class="dv">75</span>, <span class="dv">20</span>), <span class="at">smoker=</span><span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Examples <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">test_result =</span> <span class="fu">Whickham_classifier</span>(age, smoker, <span class="at">threshold=</span><span class="fl">0.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age smoker test_result
1  75    Yes           -
2  20     No           +</code></pre>
</div>
</div>
</div>
</div>
<p>Having built a classifier, we are ready to check the performance of the classifier in terms of false positive and false negative rates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Whickham <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">test_result =</span> <span class="fu">Whickham_classifier</span>(age, smoker, <span class="at">threshold=</span><span class="fl">0.6</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(outcome, test_result) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tally</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n<span class="sc">/</span><span class="fu">nrow</span>(Whickham))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   outcome [2]
  outcome test_result     n proportion
  &lt;fct&gt;   &lt;chr&gt;       &lt;int&gt;      &lt;dbl&gt;
1 Alive   -             179     0.136 
2 Alive   +             766     0.583 
3 Dead    -             301     0.229 
4 Dead    +              68     0.0518</code></pre>
</div>
</div>
<p>Evidently, a + test result is a prediction that the person will be alive on follow-up. Consequently, the (Alive, -) row has the false negatives (a negative result that is wrong). The (Dead, +) row is the false negatives. So the false-positive rate—false positives per test—is 5.2%. The false-negative rate is 13.6%.</p>
<p>We still have to explore which choice of the threshold will make the test as good as possible. Our ultimate measure is based on the consequences of the test being wrong. These consequences are encoded into the <em>loss function</em>.</p>
<p>For our purposes here, where the classifier will guide how we search for each person, the loss function could be based on the difficulty of the different kinds of searching. It is comparatively easy to check the death records, they are public, stored in a central database, and searchable by the nurse’s social insurance ID number. It’s hard to go through employment and pension records; they are private and decentralized. So we’ll define the loss function like this:</p>
<ul>
<li>loss_function(false positive) <span class="math inline">\(\equiv\)</span> 10 loss units</li>
<li>loss_function(false negative) <span class="math inline">\(\equiv\)</span> 1 loss unit</li>
</ul>
<p>With this loss function, the expected loss per test is <span class="math display">\[10 \times 0.052 + 1 \times 0.136 = 6.56\  \text{loss units per test}\]</span> To find the <em>best</em> value for the threshold, try other possible values for the threshold. Here, we’ll try 0.8, re-apply the test with that threshold, and tabulate the false-positive and false-negative rates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Whickham <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">test_result =</span> <span class="fu">Whickham_classifier</span>(age, smoker, <span class="at">threshold=</span><span class="fl">0.8</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(outcome, test_result) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tally</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n<span class="sc">/</span><span class="fu">nrow</span>(Whickham))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   outcome [2]
  outcome test_result     n proportion
  &lt;fct&gt;   &lt;chr&gt;       &lt;int&gt;      &lt;dbl&gt;
1 Alive   -             395     0.301 
2 Alive   +             550     0.419 
3 Dead    -             348     0.265 
4 Dead    +              21     0.0160</code></pre>
</div>
</div>
<p>The 0.8 threshold lowers the false positive rate to 1.6%, but raises the false negative rate to 30%. That’s the typical behavior of classifiers, changing the threshold to lower the false positive rate will raise the false negative rate, and <em>vice versa</em>.</p>
<p>With a threshold of 0.8, the expected loss per test is <span class="math display">\[10 \times 0.16 + 1 \times 0.30 = 1.9\ \text{loss units per test}\]</span> Better.</p>
<p>Before we continue on the find the <em>best</em> threshold, we need to do a <em>reality check.</em> The loss rates we just calculated are based on the training data. In that training data, there were 945 subjects who survived out of <span class="math inline">\(n=1314\)</span> altogether. That’s a prevalence of <span class="math inline">\(\frac{945}{1314} = 72\%\)</span> in the training data. It might well be that the prevalence among the remaining nurses in the study is different.</p>
<p>Accordingly, we need to adjust the loss calculations to reflect the actual prevalence. The first step in doing this is to find the <em>sensitivity</em> and <em>specificity</em>, as we did in Lesson 35.</p>
<p>Sensitivity and specificity are easy to calculate so long as you keep in mind that sensitivity is only relevant to that part of the population who actually have the condition intended to be marked by a + test. In the Whickham example, the sensitivity is the percentage of correct results <strong>only</strong> among the people whose outcome is “Alive.” There are 395 + 550 such people, of whom 550 had a correct result, so</p>
<p>sensitivity (using the theshold 0.8) is <span class="math inline">\(550/(395+550) = 58\%\)</span>.</p>
<p>Similarly, specificity is only relevant to the people whose outcome is “Dead”. There are 348 + 21 such people, of whom 348 got the correct test result.</p>
<p>specificity (using the threshold 0.8) is <span class="math inline">\(348/(348 + 21) = 94\%\)</span>.</p>
<p>Sensitivity and specificity measure the test itself. False positive and false negative rates measure the test as applied to a specific population. The relevant fact of the population is the “<strong>prevalence</strong>” of the condition.</p>
<section id="prevalence-in-the-population" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="prevalence-in-the-population"><span class="header-section-number">17.1</span> Prevalence in the population</h2>
<p>It often happens that the data used to <em>train</em> a classifier function is not representative of the population in which it will be used. For example, classifiers are often trained on “<strong>case-control</strong>” data. People with a particular condition, say, having strong symptoms of COVID-19 are easily recruited at health clinics. These are the “cases.”</p>
<p>The “controls” are people who don’t have any symptoms. These can be recruited by, say, door-to-door canvasing of a neighborhood. If we recruit 500 cases and 500 controls, then the prevalence of COVID-19 symptoms in our database will be 50%.</p>
<p>Assume for the sake of an example that the sensitivity of an inexpensive, over-the-counter COVID-19 test is 90%, and the specificity is 95%. From these numbers, we can calculate the false-positive and false-negative rates.</p>
<p>False negatives can only arise in the part of the population who have the condition. For the 500 cases in our database, the sensitivity of 90% will work out to 450 correct positive tests and 50 incorrect negative tests.</p>
<p>False positives can only arise among the people who do not have the condition. For the 500 controls in our database, the specificity of 95% will work out to 475 correct negative tests and 25 incorrect positive tests.</p>
<p>There are 1000 people in the database, so the false-positive rate is 25/1000 = 2.5%. The false-negative rate is 50/1000 = 5%.</p>
<p>However, these rates are not necessarily representative of the rates we will find when the test is used in the general population. Fortunately, we can calculate the false-positive and false-negative rates for a population with any given prevalence.</p>
<p>Imagine, say, that we think the prevalence of COVID-19 in the general population is 4%. This puts the false-negative rate—remember, false-negative only applies to people with the condition—at <span class="math inline">\(4\% \times (1-\text{sensitivity|) = 0.04 \times 0.10 = 0.004$.

In that population, 96% do not have COVID-19. This, combined with the specificity, allows calculation of the false-positive rate: $96\% \times (1-\text{specificity}) = 0.96 \times 0.05 = 0.48.

## Sensitivity and specificity as likelihoods

In Lesson 34, we used training data to estimate the sensitivity and specificity of the test in the C vs H classifier. In that example, the sensitivity was 90% and the specificity was 85%. We can use those facts to construct the test results on a hypothetical population with whatever *prevalence* we think is relevant to the actual population we will be testing. The arithmetic is straightforward, but we will use graphics to illustrate the calculations.

First, we synthesis a data frame that has many rows, half corresponding to imaginary people with condition C and the other half with condition H. Next, we assign a *test outcome* for each of the people. We do this in a way that duplicates the sensitivity and specificity that we measured earlier. That is, for the C people, we randomly generate a + or - test result, setting the probability of a + result to be the measured *sensitivity*. We do similarly for the H people, the only difference being that the probability of a - result will be the *specificity*. Figure @fig-planets-of-C-and-H shows 2000 rows of simulated data, with 1000 C cases and 1000 H cases.


::: {.cell}
::: {.cell-output-display}
![Knowing the specificity and sensitivity of the test, we can create hypothetical worlds to use in a simulation.)](Reading-notes-lesson-35_files/figure-html/fig-planets-of-C-and-H-1.png){#fig-planets-of-C-and-H width=672}
:::
:::


@fig-planets-of-C-and-H shows the simulated data split up into two groups, one for the C cases and the other for the H cases.

Now we are going to push hard on a fanciful metaphor in order to introduce some new terminology that will be important for Lessons 36 and 37. The metaphor is that C people originate in a *planet* populated exclusively by C people. The H people live on another planet, inhabited only by the H. On both planets, the classifier has been applied to everyone so that we know their test results: + is shown in blue, - in gray, as in Lesson 34.

Needless to say, these planets are imaginary. Let's call them "**hypothetical**" planets, planets where a particular hypothesis is known to apply. The hypothesis on the C planet is that all the inhabitants are C. Likewise for the H planet. The proportion of + test results on Planet C has been set to match the actual *sensitivity* of the classifier. Similarly, the - test results on Planet H match the actual *specificity* of the classifer.

A new bit of statistical vocabulary that will be important in Lessons 36 and 37. A
"**likelihood**" is a special kind of probability. Like all probabilities, it's a number between zero and one. Likelihoods are always conditional probabilities, that is a probability calculated on the assumption that a specific assumption holds. In terms of our metaphor, a likelihood is a probability calculated on a hypothetical planet.

The sensitivity is a likelihood. The hypothetical planet is Planet C, the planet where all inhabitants have condition C. On that planet, the sensitivity is the probability that a randomly selected inhabitant will get a test result +. But, since the probability is being calculated on the condition that all inhabitants have condition C, it is a conditional probability: a likelihood.

The specificity is similarly a likelihood. The hypothetical planet is H, where all inhabitants have condition H. The conditional probability is that of getting a - result on the hypothetical planet.

We will denote likelihoods using the letter ${\cal L}$. The fanciful script reminds us that the likelihood is a fanciful probability, a probability on a hypothetical world.

The sensitivity is ${\cal L}(+ \text{ given } C)$. The specificity is ${\cal L}(- \text{ given } H)$. The "given C" means "on hypothetical planet C. The "given H" means "on hypothetical planet H." It would be just as correct to write $p(+\text{ given }C)$ and $p(-\text{ given }H)$, but I want to remind you that the the sensitivity and specificity apply only to their respective conditions, C and H. Also, phrases like "assuming H, the probability of - is ..." or "under the assumption H, the probability of - is ...."

::: {.callout-note}
## Constructing a world with a given prevalence

Now to use the hypothetical planets C and H to construct a realistic world. By "realistic" we mean that the sensitivity and specificity are right *and* that the prevalence matches that of the target population in which the classifier is going to be used.

As notation, let's write the prevalence as $p(C)$. This is a probability, one that we will make up in order to define the target population. Notice that $p(C)$ does not have any condition. We knew it from previous studies of the target population. For this reason, it's appropriate to call $p(C)$ by a special name: the **prior** probability. The twin probability, $p(H)$ is also a prior probability. Since C and H are the only possibilities it must be that $p(H) = 1 - p(C)$.

To construct a realistic world, we're going to import people from hypothetical planets C and H. Remember, on C everyone has condition C; on H, everyone has condition H. How many people to import from each hypothetical planet? To put $N$ people on the realistic world, we will take $N p(C)$ from planet C, and $N (1-p(C))$ from planet H. The world thus populated, with $N=500$ and $p(C)$ set to 30% is shown in @fig-prevalence-world.


::: {.cell}
::: {.cell-output-display}
![The world created to have prevalence $p(C) = 30\%$ and $N=500$ inhabitants. This world has 150 immigrants from Planet C and 350 from Planet H.](Reading-notes-lesson-35_files/figure-html/fig-prevalence-world-1.png){#fig-prevalence-world width=672}
:::
:::


While it's feasible to do the calculations as a simulation on a computer, the mathematics is not so tricky. For example, we can compute the false-positive and false-negative rates on the realistic world:

- False positive rate:  $\left(1 - \underbrace{{\cal L}(+ \text{ given } C)}_\text{sensitivity}\right)\cdot \underbrace{p(C)}_\text{prevalence}$

- False negative rate: $\left(1 - \underbrace{{\cal L}(- \text{ given } H)}_\text{specificity}\right) \cdot \left(1-\underbrace{p(C)}_\text{prevalence}\right)$

:::

## From the patient's point of view

Having created and populated the realistic world, we can compute quantities that are useful in communicating with patients and doctors. For example, suppose a patient has just gotten a positive test. How certain an indication is this of the patient's having the condition C?

On the realistic world, there are two groups who get a positive test. One group is the people who genuinely have C and who also have a positive test. These are the true positives. The relative size of this group is $P(+ \text{ given } C) \equiv \text{proportion of true positives} = {\cal L}(+ \text{ given } C)\cdot p(C)}\)</span>.</p>
<p>The other group is the false positives, the people who have condition H but nonetheless received a + test. The relative size of this group is <span class="math inline">\(P(+ \text{ given } H) \equiv \text{proportion of false positives} = {\cal L}(+ \text{ given } H)\cdot p(H)\)</span>. We can calculate the size of this group since <span class="math inline">\(p(H) = 1-p(C)\)</span> and <span class="math inline">\({\cal L}(+ \text{ given } H) = 1 - {\cal L}(+ \text{ given } H)\)</span>.</p>
<p>Consequently, the probability that a + test result will be true is <span class="math display">\[\frac{{\cal L}(+ \text{ given } C)\cdot  p(C)}{{\cal L}(+ \text{ given } C)\cdot p(C) + {\cal L}(+ \text{ given } H)\cdot p(H)}\]</span></p>
</section>
<section id="for-the-patient-with-a-test-result" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="for-the-patient-with-a-test-result"><span class="header-section-number">17.2</span> For the patient with a + test result</h2>
<p>The above formula looks daunting, but we know each of the quantities and can do the arithmetic.</p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Demonstration
</div>
</div>
<div class="callout-body-container callout-body">
<p>For instance, in the example in Lesson 34 we stipulated that the prevalence <span class="math inline">\(p(C) = 4\%\)</span>. This, of course, implies that <span class="math inline">\(p(H) = 96\%\)</span>. The sensitivity was stipulated at 90%, that is, <span class="math inline">\({\cal L}(+ \text{ given } C) = 90\%\)</span>. The specificity was 85%, meaning that <span class="math inline">\({\cal L}(+ \text{ given } H) = 15\%\)</span>. Putting these values together in the formula tells us that the probability that a person with a + test actually having the condition C is:</p>
<p><span class="math display">\[\frac{0.90 \cdot 0.04}{0.90 \cdot 0.04 + 0.15\cdot 0.96} = 20\%\]</span> That’s good news to the Lesson 34 patient who gets a positive test result: He or she has only a 20% chance of having condition C.</p>
<p>Now consider the situation of a patient in the world of <span class="quarto-unresolved-ref">?fig-prevalence-world</span>. There, the population has a prevalence of 30% rather than 4%. This changes the meaning of a + test. The probability of being C given a + test is:</p>
<p><span class="math display">\[\frac{0.90 \cdot 0.30}{0.90 \cdot 0.30 + 0.15\cdot 0.70} = 72\%\]</span></p>
<p>In a population where the prevalence is high, a + test is more likely to mean what it suggests.</p>
</div>
</div>
<p>Since the reliability of a + result differs depending on the prevalence of C, it often happens that medical screening tests are recommended for one group of people but not for another.</p>
<p>For instance, the US Preventative Services Task Force (USPSTF) issues recommendations about a variety of medical screening tests. According to the Centers for Disease Control (CDC) summary:</p>
<blockquote class="blockquote">
<p><em>The USPSTF recommends that women who are 50 to 74 years old and are at average risk for breast cancer get a mammogram every two years. Women who are 40 to 49 years old should talk to their doctor or other health care provider about when to start and how often to get a mammogram.</em></p>
</blockquote>
<p>Recommendations such as this can be baffling. Why recommend mammograms only for people 50 to 74? Why not for older women as well? And how come women 40-49 are only told to “talk to their doctor?”</p>
<p>The CDC summary needs decoding. For instance, the “talk to [your] doctor” recommendation really means, “We don’t think a mammogram is useful to you, but we’re not going to say that straight out because you’ll think we are denying you something. We’ll let your doctor take the heat, although typically if you ask for a mammogram, your doctor will order one for you. If you are a woman younger than 40, a mammogram is even less likely to give a useful result, so unlikely that we won’t even hint you should talk to a doctor.”</p>
<p>The reason mammograms are not recommended for women 40-49 is that the prevalence for breast cancer is much lower in that group of people than in the 50-74 group. The prevalence of breast cancer is even lower in women younger than 40.</p>
<p>So what about women 75+? The prevalence of breast cancer is high in this group, but at that age non-treatment is likely to be the most sensible option. Cancers can take a long while to develop from the stage identified on a mammogram, and at age 75+ it’s not likely to be the cause of eventual death.</p>
<p>The <a href="https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/breast-cancer-screening">USPSTF web site</a> goes into some detail about the reasoning for their recommendations. It’s worthwhile reading to see what considerations went into their decision-making process.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Reading-notes-lesson-34.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Constructing a classifier</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Reading-notes-lesson-36.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>