<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Danny Kaplan">
<meta name="dcterms.date" content="2022-11-16">

<title>Lessons in Statistical Thinking - 3&nbsp; Signal and noise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Reading-notes-lesson-22.html" rel="next">
<link href="./Reading-notes-lesson-20.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Signal and noise</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Lessons in Statistical Thinking</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preliminaries</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-19.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistical thinking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-20.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Measuring and simulating variation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-21.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Signal and noise</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-22.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling variation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-23.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimating sampling variation from a single sample</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-24.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Effect size</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-signal-and-noise" id="toc-sec-signal-and-noise" class="nav-link active" data-scroll-target="#sec-signal-and-noise"> <span class="header-section-number">3.1</span> Signal and noise</a></li>
  <li><a href="#measuring-variation" id="toc-measuring-variation" class="nav-link" data-scroll-target="#measuring-variation"> <span class="header-section-number">3.2</span> Measuring variation</a></li>
  <li><a href="#dags-from-data" id="toc-dags-from-data" class="nav-link" data-scroll-target="#dags-from-data"> <span class="header-section-number">3.3</span> DAGs from data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Signal and noise</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Danny Kaplan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 16, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>Imagine being transported back to June 1940 . You and your family might be sitting around a radio receiver, having just switched on set and waited for it to warm up in time to hear a news broadcast. I’ve selected a newscast for you, recording 103. The recording covers the surrender of the French in the face of the German invasion. Press the play button in the box below and listen.</p>
<iframe src="https://archive.org/details/1940RadioNews/1940-06-21-CAN-WIlliam-C-Kirker-On-French-Armistace-At-Compiegne.mp3" width="100%" height="400" style="border:1px solid black;">
</iframe>
<p>There are many other recordings on the site which are worth listening to. I’m directing you to <a href="https://archive.org/details/1940RadioNews/1940-06-21-CAN-WIlliam-C-Kirker-On-French-Armistace-At-Compiegne.mp3">#103</a> as an example of a radio phenomenon: <strong>noise</strong> (or, in slang, “static”). You can clearly make out the spoken words from the recording. But there is also a background sound, something like the sound made by the act of crumpling paper.</p>
<p>Modern radio engineering has more-or-less eliminated noise, mainly by the use of digital technology. (Many of the recordings on the radio archive site have been “cleaned” so the noise is not so evident.) But if you have ever talked to a friend at a sporting event, you have probably had to shout to get your message over the noise of the crowd. At the receiving end, your friend intuitively filters out the noise (unless it is too loud) and recovers your words.</p>
<p>Engineers and others make a distinction between <strong>signal</strong> and noise. The signal is the spoken words of the 1940 broadcast, the noise is the hiss and clicks. You can intuitively separate the signal and the noise in this recording, focusing attention on the signal and ignoring the noise.</p>
<p>Separating signal from noise—or, at least trying to reduce the noise—is a common problem in all sorts of settings. Historically, statistics emerged from a confluence of two needs: i) the need to summarize the resources and activities of countries and <strong>states</strong> (whence comes the “stat” in “statistics”) and ii) the need to filter out noise so that the signal becomes clearer.</p>
<section id="sec-signal-and-noise" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-signal-and-noise"><span class="header-section-number">3.1</span> Signal and noise</h2>
<p>To illustrate the statistical problem of signal and noise, let’s turn to a DAG simulation: <code>dag01</code>. Here’s a sample from <code>dag01</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(dag01, <span class="at">size=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
       x     y
   &lt;dbl&gt; &lt;dbl&gt;
1 -0.326  2.84
2  0.552  5.04</code></pre>
</div>
</div>
<p>The DAG simulation implements a relationship between <code>x</code> and <code>y</code>. In statistics, this <em>relationship</em> is the signal.</p>
<blockquote class="blockquote">
<p>Look at the 2-row sample from the simulation and make a guess about what the relationship is.</p>
</blockquote>
<p>Your guess will be exactly that: a guess. Any of an infinite number of possible relationships could account for the <code>x</code> and <code>y</code> data. The noise reduction problem of statistics is to make the guess as good as possible. For a sample of size <span class="math inline">\(n=2\)</span>, as good as possible is not very good!</p>
<p>To have a better shot at revealing the relationship hidden by the noise, we need more data, a bigger sample. Here’s a sample of size <span class="math inline">\(n=10\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(dag01, <span class="at">size=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
         x     y
     &lt;dbl&gt; &lt;dbl&gt;
 1 -0.786  1.89 
 2  0.0547 4.12 
 3 -1.17   2.36 
 4 -0.167  6.33 
 5 -1.87   0.933
 6 -0.120  2.93 
 7  0.826  5.70 
 8  1.19   5.90 
 9 -1.09   2.13 
10 -0.375  4.23 </code></pre>
</div>
</div>
<p>Looking carefully at the two rows of data you may be able to see some patterns. <code>x</code> is never larger than, say, 2 in magnitude and can be positive or negative. <code>y</code> is always positive. And notice that when <code>x</code> is negative, the corresponding <code>y</code> value is relatively small compared to the <code>y</code> values for positive <code>x</code>.</p>
<p>With the bigger sample size, <span class="math inline">\(n=10\)</span> versus <span class="math inline">\(n=2\)</span>, we can make a more informed guess about the relationship between variables <code>x</code> and <code>y</code>.</p>
<p>Human cognition is not well suited to looking a long columns of numbers. Often, we can make better use of our natural human talents by translating the sample into a graphic, like this:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Reading-notes-lesson-21_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Collecting more data can make the relationship clearer. Here’s a graph of a sample of size <span class="math inline">\(n=10,000\)</span> with the smaller <span class="math inline">\(n=10\)</span> sample shown in orange:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-xy-relationship-large" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-21_files/figure-html/fig-xy-relationship-large-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 3.1: With <span class="math inline">\(n=10,000\)</span> rows, the relationship between <code>x</code> and <code>y</code> is evident graphically.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>There are many ways to describe the relationship between <code>x</code> and <code>y</code> indicated by the graph of the large sample. For instance, we can see that when <code>x</code> is positive, <code>y</code> is almost always greater than 4, but for negative <code>x</code> the value of <code>y</code> tends to be less than 4.</p>
<p>In this course, we prefer to make quantitative summaries of relationships. We do this by fitting models to the data. Here’s the relationship that’s shown by the original sample of 10:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> original) <span class="sc">%&gt;%</span> <span class="fu">coefficients</span>() <span class="co"># size 10 sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           x 
   4.262846    1.741758 </code></pre>
</div>
</div>
<p>The coefficients in this model correspond to the mathematical relationship <span class="math inline">\(y = 4.26 + 1.74 x\)</span>. On it’s own, this formula doesn’t tell us the extent to which we have filtered out the noise in the simulation.</p>
<p>With more data, say, the larger sample of <span class="math inline">\(n=10,000\)</span>, the relationship becomes more evident:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> larger) <span class="sc">%&gt;%</span> <span class="fu">coefficients</span>() <span class="co"># size 10 sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           x 
   4.008928    1.495904 </code></pre>
</div>
</div>
<p>Because these data come from a DAG simulation, we can look at the formulas to see exactly what relationship is behind the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dag01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
x ~ eps()

[[2]]
y ~ 1.5 * x + 4 + eps()

attr(,"class")
[1] "list"      "dagsystem"</code></pre>
</div>
</div>
<p>Comparing the two models to the DAG formula for <code>y</code>, we can see that the larger sample produced coefficients that are much closer to the formula than did the smaller sample. Closer, but not exactly the same. Even in the coefficients calculated from the large sample, there is still a legacy of the noise in the original relationship.</p>
<p>The lesson here is simple: <em>More data can give a better view of the relationships.</em></p>
<p>The challenge we face when working with data generated in the real world is that it is not often possible to open the black box that generated the data; all we have is the data! So how can we tell whether the data we have at hand are sufficient for giving a faithful description of the actual relationships?</p>
<p>The general idea is to use the variation within the sample to accomplish two things at once: i. make a description of the relationship, and ii. estimate how much inherited noise there is in the description. The result of (ii) is important, since it can tell us whether or not our description (i) is good enough for the purpose we seek to serve.</p>
<p>To get started, let’s explore how to measure the amount of variation in the data. This can give us an idea of the size of the overall signal+noise, which we will do in the next section of this Lesson. In Lesson 22 we will use DAG simulations to get an idea of how to estimate the amount of inherited noise in the description of the relationship. The DAG simulation is useful because we have access to the internal mechanism of the DAG, so it is easy to see how close the description is to the actual relationship.</p>
<p>In Lesson 23, we will take off the DAG training wheels and learn how to estimate the size of the inherited noise in the description directly from data, without having to open the black box of the mechanism that generated the data. If you think about it, it is an amazing claim that we can estimate how close our data-driven description is to the actual mechanism, without having to know the actual mechanism!</p>
</section>
<section id="measuring-variation" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="measuring-variation"><span class="header-section-number">3.2</span> Measuring variation</h2>
<p>We already know the standard way to measure variation in a single variable: the <strong>variance</strong> or, equivalently, the <strong>standard deviation</strong>, which is simply the square root of the variance.</p>
<p>Perhaps you are wondering why there are <em>two</em> standard ways to measure variation, when each can be calculated from the other? The variance can be found by squaring the standard deviation, the standard deviation by taking the square root of the variance. Either will do, so why both?</p>
<p>The answer to this question is illustrated by a bit of geometry: the mathematics of right triangles and the corresponding Pythagorean relationship among the sides of the triangle: <span class="math inline">\(A^2 + B^2 = C^2\)</span>. The quantities <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, and <span class="math inline">\(C\)</span> are the lengths of the edges of the right triangle. The quantities <span class="math inline">\(A^2\)</span>, <span class="math inline">\(B^2\)</span> and <span class="math inline">\(C^2\)</span> are the lengths-<em>squared</em> of those edges. In order to calculate the length of one edge given the lengths of the others, we need first to square the lengths. Having squared them, we can easily do the calculation of the length-squared of the unknown edge. Then, we take the square root of the length-squared to find the length of the edge.</p>
<p>Lengths are like standard deviations, lengths-squared are like the variance. Where does the right triangle fit in? The overall variation in the response variable is like the hypothenuse of a right triangle. One of the other two edges represents the <em>noise</em> in the relationship. The other edge represents the <em>signal</em>: the relationship itself. It’s easy to measure the overall variation in the response variable. We can also measure the noise, but indirectly. First, we fit a model connecting the response variable to the explanatory variable(s). Then the variation of the <strong>residuals</strong> for that model are the estimate for the noise.</p>
<p>Our first illustration will use data from <code>dag01</code>. We will arbitrarily set the sample size to <span class="math inline">\(n=10,000\)</span>. (In Lesson 22, we will look at the impact of sample size on the results.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Dag_data <span class="ot">&lt;-</span> <span class="fu">sample</span>(dag01, <span class="at">size=</span><span class="dv">10000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now measure the variation in <code>x</code> and <code>y</code> in the standard way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Dag_data <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">sx =</span> <span class="fu">sd</span>(x), <span class="at">sy =</span> <span class="fu">sd</span>(y), <span class="at">vx =</span> <span class="fu">var</span>(x), <span class="at">vy =</span> <span class="fu">var</span>(y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
     sx    sy    vx    vy
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.998  1.81 0.995  3.29</code></pre>
</div>
</div>
<p>The size of the <code>x</code> variation is about 1. The size of the <code>y</code> variation is about 1.7. (We’re using the standard deviation to measure the size of the variation.</p>
<p>Look again at the formulas that compose <code>dag01</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dag01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
x ~ eps()

[[2]]
y ~ 1.5 * x + 4 + eps()

attr(,"class")
[1] "list"      "dagsystem"</code></pre>
</div>
</div>
<p>From the formula for <code>x</code> we can see that <code>x</code> comes from a random number generator, <code>eps()</code>. The <code>eps()</code> generator is designed to generate noise of size 1 by default.</p>
<p>As for <code>y</code>, the formula includes two sources of variation:</p>
<ol type="1">
<li>The part of <code>y</code> determined by <code>x</code>, that is <span class="math inline">\(y = \mathbf{1.5 x} + \color{gray}{4 + \text{eps()}}\)</span></li>
<li>The noise added directly into <code>y</code>, that is <span class="math inline">\(y = \color{gray}{\mathbf{1.5 x} + 4} + \color{blank}{\mathbf{eps(\,)}}\)</span></li>
</ol>
<p>The 4 in the formula doesn’t add any <em>variation</em> to <code>y</code>; it’s just a number.</p>
<p>Let’s measure variation using the standard deviation: We already know that <code>eps()</code> generates variation of size 1. So the amount of variation contributed by the <code>+ eps()</code> term in the DAG formula is 1. The remaining variation is contributed by <code>1.5 * x</code>. The amount of variation in <code>x</code> is 1, coming from the <code>eps()</code> in the formula for <code>x</code>. A reasonable guess is that <code>1.5 * x</code> will have 1.5 times the variation in <code>x</code>. So, the variation contributed by the <code>1.5 * x</code> component is 1.5. The overall variation in <code>y</code> is the sum of the variations contributed by the individual components. This suggests that the variation in <code>y</code> should be <span class="math display">\[\underbrace{1}_\text{from eps()} + \underbrace{1.5}_\text{from 1.5 x} = \underbrace{2.5}_\text{overall variation in y}.\]</span> Simple addition! Unfortunately, the result is wrong. In the previous <code>summarize()</code> of the <code>Dag_data</code>, we measured the overall variation in <code>y</code> as about 1.72.</p>
<p>Let’s try again, this time using the <em>variance</em> as our measure of variation.</p>
<p>Since <code>eps()</code> generates variation whose standard deviation is 1, the variance is simply <span class="math inline">\(1^2 = 1\)</span>. The variance of <code>x</code> is therefore 1, as is the variance of the <code>eps()</code> component of <code>y</code>.</p>
<p>What’s the variance of <code>1.5 * x</code>? It turns out to be <span class="math inline">\(1.5^2\, \text{var(}\mathit{x}\text{)} = 2.25\)</span>. Adding up the variances from the two components gives</p>
<p><span class="math display">\[\text{var(}\mathit{y}\text{)} = \underbrace{2.25}_\text{from 1.5 eps()} + \underbrace{1}_\text{from eps()} = 3.25\]</span></p>
<p>This result, that the variance of <code>y</code> is 3.25, is a close match to what we found in summarizing the <code>y</code> data generated by the DAG. And, of course, <span class="math inline">\(\sqrt{3.25} = 1.80\)</span>, which is what we found by calculating the standard deviation of the <code>y</code> directly from the data.</p>
<p>The lesson here: When adding two sources of variation, the variances of the individual sources add to produce the overall variance of the sum. Just like <span class="math inline">\(A^2 + B^2 = C^2\)</span>.</p>
</section>
<section id="dags-from-data" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="dags-from-data"><span class="header-section-number">3.3</span> DAGs from data</h2>
<p>In modeling data from <code>dag01</code> we could recover the DAGs formula for <code>y</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(dag01, <span class="at">size=</span><span class="dv">10000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> .) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           x 
   3.996846    1.494939 </code></pre>
</div>
</div>
<p>It is wrong to think that from data we can determine the DAG that generated the data. It’s only if we know the structure of the data-generation DAG that we can recover the mechanism inside that DAG. But another statistical thinker might claim that what’s behind the data is <code>y</code> causing <code>x</code>. Based on this assumption, she also can find the mechanism inside her hypothesized DAG:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(dag01, <span class="at">size=</span><span class="dv">10000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(x <span class="sc">~</span> y, <span class="at">data =</span> .) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           y 
 -1.8485902   0.4635813 </code></pre>
</div>
</div>
<p>A DAG is a <strong>hypothesis</strong>, a statement that might or might not be true. DAGs are part of the statistical apparatus for thinking responsibly about <strong>causality</strong>. You use a DAG—or, potentially, multiple DAGs—when the issue of what causes what is relevant to your work.</p>
<p>When there are only two variables involved in the system under consideration—we’ll call them X and Y for simplicity—there are only two possible DAGs:</p>
<p><span class="math display">\[X \rightarrow Y\ \ \ \ \ \text{and}\ \ \ \ \ X \leftarrow Y\]</span></p>
<p>Often, but not always, our understanding of the world allows us to focus on one of these and not the other. Example: Does the rooster crowing cause the sun to rise, or does the rising sun cause the rooster to crow? That’s a pretty easy question if you know how things work.</p>
<p>But there are additional DAG possibilities that can account for the relationship between <code>x</code> and <code>y</code>. For instance, if we introduce another quantity, <code>c</code> in between <code>x</code> and <code>y</code>, four other DAGs need to be considered:</p>
<p><span class="math display">\[X \rightarrow C \rightarrow Y \ \ \ \ \ \text{and}\ \ \ \ \
X \leftarrow C \leftarrow Y \ \ \ \ \ \text{and}\ \ \ \ \
X \leftarrow C \rightarrow Y \ \ \ \ \ \text{and}\ \ \ \ \
X \rightarrow C \leftarrow Y\]</span></p>
<p>Actually, there are many other configurations of DAGs involving three variables. To keep things simple, we’ll restrict things to DAGs where X might or might not cause Y, but Y never causes X. (We don’t lose anything from this restriction because you get to make the choice of what real-world variable correspond to X and which one to Y.) <a href="#fig-ten-triples">Figure&nbsp;<span>3.2</span></a> shows the 10 configurations of 3-variable DAGs where Y doesn’t cause X.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ten-triples" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="www/ten-triples.png" class="img-fluid figure-img" width="167"></p>
<p></p><figcaption class="figure-caption">Figure 3.2: Ten DAG configurations involving three variables X, Y, and C and where there is no causal path going from Y to X.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The statistical thinker, with the conceptual tool of DAGs at, can consider multiple possibilities for what might cause what. Sometimes she will be able to discard some of the possibilities based on common sense. (Think: roosters and the sun.) But other times there may be possibilities that she doesn’t favor but which nonetheless might be plausible to other people. In Lesson 28 we will explore how each configuration of DAG has implications for which model formulas can or cannot reveal the hypothesized causal mechanism.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Reading-notes-lesson-20.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Measuring and simulating variation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Reading-notes-lesson-22.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling variation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>