<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Danny Kaplan">
<meta name="dcterms.date" content="2022-10-26">

<title>Spring 2023 Math 300 Revisions - Math 300R NTI Lesson r (lesson &lt;- 19)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Spring 2023 Math 300 Revisions</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lessons.html">Lessons</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../layout.html">Site layout</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../objective-list.html">Objectives</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../LC-list.html">LCs</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Math 300R NTI Lesson 19</h1>
<p class="subtitle lead">Decisions with data</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Danny Kaplan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 26, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Question about software in draft
</div>
</div>
<div class="callout-body-container callout-body">
<p>Should we use a <code>fitmodel()</code> command modeled on <code>rigr::regress()</code> that does the right thing (linear versus logistic regression, count regression, …) based on the response variable? It will have data as the first argument, enabling <code>sample()</code> to be piped into the function. Return the model object, but have the model function (which will be in probability for logistic regression) available for extraction via <code>makeFun()</code>. Allow <code>makeFun()</code> to specify whether to return probability, odds, or log odds from a logistic regression model.</p>
</div>
</div>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<p>19.1 Distinguish between the two settings for decision-making:</p>
<ol type="a">
<li><strong>Prediction</strong>: predict an outcome for an individual</li>
<li><strong>Relationship</strong>: characterize a relationship with an eye toward intervention or a better understanding of how a mechanism works.</li>
</ol>
<p>19.2 Given a research question, identify whether it corresponds to a prediction setting or a relationship setting.</p>
<p>19.3 Understand the covering of a variable by an interval specified by a coverage level (e.g.&nbsp;0.95).</p>
<p>19.4 Use “violin” plots to display the density of a variable. (This should really go in the first half of the course, but ModernDive doesn’t do it.)</p>
</section>
<section id="reading" class="level2">
<h2 class="anchored" data-anchor-id="reading">Reading</h2>
<p>TBD</p>
</section>
<section id="lesson" class="level2">
<h2 class="anchored" data-anchor-id="lesson">Lesson</h2>
<p><em>This lesson marks the beginning of a new phase of the course. Thus far, we’ve worked with </em>techniques* for data wrangling, graphics, and regression modeling. Now we address the question of what a regression model (and other information that we might have) can tell us about the real world.*</p>
<div class="callout-tip callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Setup
</div>
</div>
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaicData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Guided activity: House prices
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Have students do the calculations for the first model, answering the questions that follow. After this is complete, have students do the calculations for the second model and answer those questions.</em></p>
<p>The <code>mosaicData::SaratogaHouses</code> data frame contains information about the sales price and various attributes of about 1700 houses. (See <code>?SaratogaHouses</code> for a detailed description.)</p>
<p>Do a regression of <code>price ~ bedrooms</code> and explain what the regression coefficients mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(price <span class="sc">~</span> bedrooms, <span class="at">data=</span>SaratogaHouses) <span class="sc">|&gt;</span> <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)    bedrooms 
   59862.96    48217.81 </code></pre>
</div>
</div>
<ol type="1">
<li><p>What are the units of the intercept and of the <code>bedrooms</code> coefficient? *Intercept in dollars, <code>bedrooms</code> in dollars per bedroom.</p></li>
<li><p>Interpret what the coefficients indicate about the price of houses and bedrooms. <em>Each additional bedroom adds about $50000 to the value of a house.</em></p></li>
<li><p>According to the model, predict what would be the sales price (at the time the data was collected, 2006) of a house with two bedrooms? <em><span class="math inline">\(59863 + 2\times 48218\)</span></em></p></li>
</ol>
<p>Of course, bedrooms are not the only important thing about a house. Let’s include <code>livingArea</code> along with <code>bedrooms</code> in the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(price <span class="sc">~</span> livingArea <span class="sc">+</span> bedrooms, <span class="at">data=</span>SaratogaHouses) <span class="sc">|&gt;</span> <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)  livingArea    bedrooms 
  36667.895     125.405  -14196.769 </code></pre>
</div>
</div>
<ol type="1">
<li>What are the units of the <code>livingArea</code> coefficient? <em>dollars per square foot</em></li>
<li>What does this model say about the value of adding a bedroom? <em>It seems to reduce the value of the house by about $15,000.</em></li>
</ol>
<p>Based on exactly the same data, the two models seem to give contradictory statements about the value of an additional bedroom.</p>
<ol type="i">
<li>Is one model right and the other wrong? If so, which one is right? (Explain your reasoning.) <em>Both models are mathematically correct. But they need to be interpreted in different ways. Each is telling us something different about the real world.</em></li>
<li>Could both models be right? If so, explain why the <code>bedroom</code> coefficients have opposite signs. <em>We will need to develop some additional tools and concepts before we can take on this question.</em></li>
</ol>
<p>Learning how to interpret models in terms of what they say about the world is a major theme of this second half of Math 300.</p>
<p>Another, more technical question that we will address has to do with the <em>precision</em> of coefficients like 125.40 dollars per square foot. Might it actually be $200/ft<sup>2</sup>? How about $500/ft<sup>2</sup>? And how seriously should we take the sales value that we calculate by setting numbers for <code>bedrooms</code> and <code>livingArea</code> into the model?</p>
</div>
</div>
</section>
<section id="learning-checks" class="level2">
<h2 class="anchored" data-anchor-id="learning-checks">Learning Checks</h2>
</section>
<section id="setup-1" class="level2">
<h2 class="anchored" data-anchor-id="setup-1">Setup</h2>
<p>The <code>math300</code> package will be needed for lessons 20 through 39.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(math300)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(NHANES)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="objective-2" class="level2">
<h2 class="anchored" data-anchor-id="objective-2">19.1 (Objective 2)</h2>
<p>What are the two settings for decision making that we cover in this course?</p>
<p>Give an example of each.</p>
<section id="solution" class="level3">
<h3 class="anchored" data-anchor-id="solution">Solution</h3>
<ol type="1">
<li>Prediction and (2) Relationship</li>
</ol>
<ol type="i">
<li><p>What will be the sales price of this house? <em>“This house” is a shorthand way of saying “a house with these attributes.” The sales price will be the output of a prediction function that takes the various attributes as input and produces a sales price as output.</em></p></li>
<li><p>If I look for a house with an additional bathroom, how much will that change the sales price? <em>This asks for the relationship between number of bathrooms and sales price.</em></p></li>
</ol>
<hr>
</section>
</section>
<section id="objective-2-1" class="level2">
<h2 class="anchored" data-anchor-id="objective-2-1">19.2 (Objective 2)</h2>
<p>For each of these research questions, say whether it is a prediction setting or a relationship setting.</p>
<ol type="i">
<li>What’s the risk of falling ill?</li>
<li>How will the risk of falling ill change if we eat more broccholi?</li>
<li>Is there any reason to believe, based on the evidence at hand, that we should look more deeply into the possible benefits of broccholi?</li>
</ol>
<section id="solution-1" class="level3">
<h3 class="anchored" data-anchor-id="solution-1">Solution</h3>
<ol type="i">
<li>Prediction</li>
<li>Relationship</li>
<li>Relationship</li>
</ol>
<hr>
</section>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">19.3</h2>
<p>Fit a model to some data. Write down the function implied by the coefficients.</p>
<p>Evaluate the function for:</p>
<ol type="i">
<li>a=7, b=9</li>
<li>and so on.</li>
</ol>
<section id="solution-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-2">Solution</h3>
<hr>
</section>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1">19.4</h2>
<p>About the summarization of models. Pipe the model fit into any of four functions:</p>
<ol type="i">
<li><code>%&gt;% coefficients()</code></li>
<li><code>%&gt;% broom::tidy()</code></li>
<li><code>%&gt;% rsquared()</code></li>
<li><code>%&gt;% confint()</code></li>
</ol>
<p>REDO <code>confint()</code> so that the columns are named <code>lower</code>, <code>middle</code>, <code>upper</code></p>
<section id="solution-3" class="level3">
<h3 class="anchored" data-anchor-id="solution-3">Solution</h3>
<hr>
</section>
</section>
<section id="obj.-19.3" class="level2">
<h2 class="anchored" data-anchor-id="obj.-19.3">19.5 (Obj. 19.3)</h2>
<p>Calculation of a 95% coverage interval (or any other percent level interval) is straightforward with the right software. To illustrate, consider the efficiency of cars and light trucks in terms of CO_2 emissions per mile driven. We’ll use the <code>CO2city</code> variable in the <code>math300::MPG</code> data frame. The basic calculation using the <code>mosaic</code> package is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">df_stats</span>( <span class="sc">~</span> CO2city, <span class="at">data =</span> math300<span class="sc">::</span>MPG, <span class="fu">coverage</span>(<span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  response   lower   upper
1  CO2city 276.475 684.525</code></pre>
</div>
</div>
<p>The following figure shows a violin plot of <code>CO2city</code> which has been annotated with various coverage intervals. Use the calculation above to identify which of the intervals corresponds to which coverage level.</p>
<ol type="1">
<li>50% coverage interval -A- (c)</li>
<li>75% coverage interval -A- (e)</li>
<li>90% coverage interval -A- (g)</li>
<li>100% coverage interval -A- (i). This extends from the min to the max, so you could have figured this out just from the figure.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="NTI-Lesson19_files/figure-html/kangaroo-freeze-candy-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="obj-19.3" class="level2">
<h2 class="anchored" data-anchor-id="obj-19.3">19.6 (Obj 19.3)</h2>
<p>The two jitter + violin graphs below show the distribution of two different variables, X and Y. Which variable has more variability?</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="NTI-Lesson19_files/figure-html/goat-take-linen-1-1.png" class="img-fluid" style="width:50.0%"></p>
</div>
<div class="cell-output-display">
<p><img src="NTI-Lesson19_files/figure-html/goat-take-linen-1-2.png" class="img-fluid" style="width:50.0%"></p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is about the same level of variability in variable A and variable B. This surprises some people. Remember, the amount of variability has to do with the spread of <em>values</em> of the variable. In variable B, those values are have a 95% prediction interval of about 30 to 65, about the same as for variable A. There are two things about plot (b) that suggest to many people that there is more variability in variable B.</p>
<ol type="1">
<li>The larger horizontal spread of the dots. Note that variable B is shown along the vertical axis. The horizontal spread imposed by jittering is completely arbitrary: the only values that count are on the y axis.<br>
</li>
<li>The scalloped, irregular edges of the violin plot.</li>
</ol>
<p>On the other hand, some people look at the clustering of the data points in graph (b) into several discrete values, creating empty spaces in between. To them, this clustering implies less variability. And, in a way, it does. But the <em>statistical</em> meaning of variability has to do with the overall spread of the points, not whether they are restricted to discrete values.</p>
</div>
</div>
<hr>
</section>
<section id="objs.-19.3-19.4" class="level2">
<h2 class="anchored" data-anchor-id="objs.-19.3-19.4">19.7 (Objs. 19.3 &amp; 19.4)</h2>
<p>The graphs below show a violin plot of body mass index (BMI) for adults and children. One of the graphs shows a correct 95% coverage interval on BMI, the other does not.</p>
<p>Identify the incorrect graph and say what feature of the graph led to your answer.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="NTI-Lesson19_files/figure-html/goat-hurt-painting-1-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="NTI-Lesson19_files/figure-html/goat-hurt-painting-1-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Graph (b) is correct. In graph (a), you can see that the interval fails to include a lot of the low BMI children and extends too high. For adults, the graph (a) interval extends too far low and doesn’t go high enough.</p>
</div>
</div>
<hr>
</section>
<section id="e" class="level2">
<h2 class="anchored" data-anchor-id="e">19.E</h2>
<p>There are two equivalent formats describing an interval numerically that are widely used:</p>
<ol type="i">
<li>Specify the lower and upper endpoints of the interval, e.g.&nbsp;7 to 13.</li>
<li>Specify the center and half-width of the interval, e.g.&nbsp;10 ± 3, which is just the same as 7 to 13.</li>
</ol>
<p>Complete the following table to show the equivalences between the two notations.</p>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Interval </th>
   <th style="text-align:left;"> bottom-to-top </th>
   <th style="text-align:left;"> plus-or-minus </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (a) </td>
   <td style="text-align:left;"> 3 to 11 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> (b) </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> 108 ± 10 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> (c) </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> 30 ± 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> (d) </td>
   <td style="text-align:left;"> 97 to  100 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> (e) </td>
   <td style="text-align:left;"> -4 to  16 </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="a">
<li>7 ± 4</li>
<li>98 to 118</li>
<li>29 to 31</li>
<li>98.5 ± 1.5</li>
<li>6 ± 10</li>
</ol>
<p>It’s a matter of judgement which format to use. The bottom-to-top notation highlights the range of the interval while the plus-or-minus notation emphasizes the center of the interval. As a rule of thumb, I suggest this:</p>
<ul>
<li>If the first two digits are different between the top and bottom of the interval, use the bottom-to-top notation. So, write 387 to 393. If the first two digits are the same, use plus-or-minus. For instancer, the ratio of the mass of the Earth to that of the Moon is 81.3005678 ± 0.0000027. This is easier to take in at a glance than the equivalent 81.3005651 - 81.3005708</li>
</ul>
</div>
</div>
<hr>
</section>
<section id="documenting-software" class="level2">
<h2 class="anchored" data-anchor-id="documenting-software">Documenting software</h2>
<ul>
<li>File creation date: 2022-10-26</li>
<li>R version 4.2.1 (2022-06-23)</li>
<li><code>tidyverse</code> package version: 1.3.2</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>