---
title: "Learning Checks Lesson 33"
---

```{r include=FALSE}
source("../_startup.R")
```

See `medGPA` from the Stat2Data package. Maybe come back to this in Lesson 34.


Maybe `Data2Stats::FlightResponse`

Maybe space shuttle Challenger o-ring data.

## 33.1

1. Convert probability to odds and log odds, and vice versa.


::: {.callout-note}
## Solution

:::

--------

## 33.XXX

A major company in big trouble is planning to lay off 20% of its employees. You work in the personnel office and have constructed a multivariate model of the probability of an individual being laid off. The effect size of the different input factors in the model are as follows:

- age over 50 years: change in log-odds 1
- software engineer: change in log-odds -0.5
- pay level: change in log-odd rate 0.2 per $10,000 above the company average of $40K

1. What are the odds of being laid off for an employee for whom you have no information about age, engineering capabilities, or pay level. -A- The risk of being laid off is 20% so the probability of not being laid off is 80%. The odds are therefore 20/80 = 0.25.

2. What are the log odds of an employee in (1) being laid off? -A- Simply the logarithm of the odds, so $\log(0.25) = -1.4$. 

3. Consider a 30-year old software engineer making $50,000 per year. 
    - What are the log odds of her being laid off? -A- At baseline, her log odds is -1.4. Being a software engineer, her log odds are lower by 0.5. But she makes more than the average pay by $10,000, which adds 0.2  to her log odds. Altogether, -1.4 - 0.5 + 0.2  = -1.7.
    - Translate the log odds into an absolute risk of her being laid off. -A- Undoing the logarithm on -1.7 gives an odds of 0.18, which corresponds to a probability of 0.18/(1 + 0.18) or 15%. 

--------

In LC 24.2, we took as baseline inputs for [this online breast-cancer risk assessment model]((https://bcrisktool.cancer.gov/calculator.html),  a 55-year-old, African-American woman who has never had a breast biopsy or any history of breast cancer, who doesn't know her BRCA status, and whose close relatives have no history of breast cancer, whose first menstrual period was at age 13 and first child at age 23.  

For this baseline case, the output of the model was a probability of 1.4% five-year risk of developing breast cancer. Finding out that one close relative has developed breast cancer elevates this risk to 2.2%. 

These are absolute risks: probabilities. The effect size is 2.2 - 1.4 = 0.8 percentage points. When risks are specified as probabilities, differences in risks are in "percentage points."

1. What *risk ratio* corresponds to the 1.4 to 2.2 change of risk? -A- This  is a simple ratio: 2.2% / 1.4% which is 1.57.

2. Suppose (hypothetically) that the risks were ten times higher: 14% and 22%. 
    a. What would be the risk ratio? -A- Still 1.57.
    b. What would be the percentage point change in absolute risk? -A- 8 percentage points.

3. Put yourself in the place of the baseline woman who has just found out that a close relative developed breast cancer. Which way of reporting a change of risk is more pertinent to your personal life? -A- The change in absolute risk. Even though the risk ratios are the same in (1) and (2), the change in absolute  risk is much greater in (2).

--------

## Example: Fraction attributable

US Federal law forbids employment discrimination based on age. (There are some exceptions, such as air-traffic controllers, whose mandatory retirement age is 56). In a discrimination lawsuit, data on who was and who was not laid-off was used to construct a model of the probability of layoff. The effect size is, as usual for a probability model, expressed in log odds.

- baseline: risk of 20%, so log odds of of -1.4.
- age over 50, add log odds of 1 ± 0.3
- software engineer, subtract log odds of 0.5 ± 0.25
- paid different from company average, subtract log odds of 0.2 ± 0.1 per $10,000 high than company average.

These estimates come from a logistic regression model `laid_off ~ over50 +  software_engineer + pay_above_average`.

1. For a laid-off employee over 50, what is the fraction attributable to age?

::: {.callout-note} 
## Solution
The baseline risk of being laid off is 20%. For the employee aged over 50 years, the log odds of the risk is -1.4 + 1 ± 0.3, or -0.7 to -0.1. Translating these log odds into probabilities gives a risk of  33% to 47%, with the range reflecting the uncertainty in the  effect size from the model. The estimated relative risk (risk ratio) for the employees over 50 ranges from 33/20 to 47/20, that is, from 1.65 to 2.35. The attributable fraction is $(RR - 1) / RR$ and therefore ranges from (1.65 - 1)/1.65 to (2.35 - 1) / 2.35 or 40% to 57%. 
:::

2. What fraction of all layoffs can be attributed to age over 50? (Population attributable fraction.) Assume that one-third of the employees are over 50.



