<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Spring 2023 Math 300 Revisions – reading-notes-lesson-24</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Spring 2023 Math 300 Revisions</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lessons.html">Lessons</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../layout.html">Site layout</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../objective-list.html">Objectives</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../LC-list.html">LCs</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">



<p>You now have a substantial toolbox for for summarizing data in ways that support statistical thinnking. Time to move to the next step: extracting actionable information from such summarizing. Why the word “actionable” in the previous sentence? Because much of the time the goal of summarizing data is to guide <strong>decision making</strong>. The setting is that you or your organization have to make a decision: administer a medicine, change a budget, raise or lower a price, respond to an evolving situation, and so on. Decisions ought to be made on an informed basis. Often, the information needed is hidden in tables of data. The statistical thinker knows how to extract information in a form that is as useful as possible to the decision maker.</p>
<p>Setting for decisions vary widely, but a useful simplification splits support for decision making into two broad categories.</p>
<ol type="1">
<li><strong>Making a prediction</strong> for an individual choice. The need for predictions arises in both mundane and in critical settings. For instance, an airline needs to set prices. They want to maximize revenue. Higher prices will bring in more money per seat, but the seats may not be filled. To make the decision, the airline needs a prediction about what the demand will be for those seats, which may vary based on day of the week, time of day, time of year, origin and destination of the flight, and so on. Another example: Merchants and social media sites have to make choices about what products or posts to display to a viewer. Merchants have many products, social media has many news feeds, tweets, blog entries to choose from. They want to predict which ones are most likely to cause you to respond, either by buying a particular product or watching a video, “news” report, and so on.</li>
</ol>
<p>Less mundane: A patient comes to an urgent-care clinic with symptoms. A decision needs to be made about what disease or illness the patient has in order to guide choices of tests and, in turn, possible treatment. The inputs to the prediction are the symptoms—neck stiffness, a tremor, and so on—as well as facts about the person—age, sex, occupation, etc. The output of the prediction will assign a probability to each of medical conditions that could cause the symptom. As new tests or measurements are done—temperature, blood pressure, white-blood-cell count, blood oxygenation, and others—they become new inputs for the prediction and the probabilities change accordingly. The television drama <em>House</em> provides in every episode an example of such evolving predictions, which clinicians call “differential diagnosis.” The word “prediction” suggests the future, but many predictions have to do with the current or past state that is as yet unknown to greater or lesser extent. Synonyms for “prediction” include “classification” (Lessons 34 and 35), “conjecture”, “guess”, “bet”, …. The phrase “informed guess” points to the idea: using information to support decision making.</p>
<ol start="2" type="1">
<li><strong>Intervening</strong> in a system. Such interventions occur on both grand scales and small: changes in government policies such as funding for pre-school education or subsidies for renewable energy, closing a road to redirect traffic or opening a new highway or bus line, changing the minimum wage, etc. Before making such interventions, it is wise to know what the consequences are likely to be. Figuring this out often requires understanding how the system works: what causes what. Without knowing this, how can you antipate the influence of the intervention on other components of the system? Also, interventions often affect many individuals: influencing the overall trend of the effect across individuals might be the goal, as opposed to a prediction for each individual affected.</li>
</ol>
<p>This lesson is focuses on two ideas that are useful for building and summarizing models of a system for the purposes of <em>intervening</em> in that system: effect size and interaction. We will need some additional concepts and tools in order to bring causality into the picture. This will have to wait until Lessons 28 through 31.</p>
<section id="effect-size-input-to-output" class="level2">
<h2 class="anchored" data-anchor-id="effect-size-input-to-output">Effect size: Input to output</h2>
<p>In an intervention you change something about the world. That might be the budget for a program, the dose of a medicine, the fuel input to an engine. The thing you change is the input. In response, something else in the world changes: reading ability of students, the patient’s seratonin levels (a neurotransmitter), the power output from the engine. The thing that changes in response to the change in input is called the “output.” Systems such as education, mental state, or aircraft have many components. The context in which the modeler works dictates which of these components ought to be considered the input and which the output. Usually the input is something that you can directly change; the output is something that changes in response.</p>
<p>The <strong>effect size</strong> is merely a statement of the amount of change in the output with respect to the input. There are two fundamental types of <em>inputs</em>, just as there are two fundamental types of variables:</p>
<ul>
<li><p>categorical: e.g., whether or not a person smokes.</p></li>
<li><p>quantitative: e.g., how many cigarettes per day a person smokes</p></li>
</ul>
<p>Similarly, there are two fundamental types of <em>outputs</em>: categorical or quantitative.</p>
<ul>
<li><p>categorical: e.g.&nbsp;whether the person develops cancer</p></li>
<li><p>quantitative: e.g.&nbsp;the lung capacity of the person</p></li>
</ul>
<p>How you properly describe an effect size depends on types of both the input and the output.</p>
<table class="table">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>input</th>
<th>output</th>
<th>effect size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>categorical</td>
<td>quantitative</td>
<td>the **amount* by which the output changes when the input changes category</td>
</tr>
<tr class="even">
<td>quantitative</td>
<td>quantitative</td>
<td>the <strong>rate</strong> of change in the output with respect to the input. Calculus students will recognize this rate as the partial derivative of the output with respect to the input.</td>
</tr>
<tr class="odd">
<td>categorical</td>
<td>categorical</td>
<td>the <em>probability</em> of being in each of the output categories when the input category is changed</td>
</tr>
<tr class="even">
<td>quantitative</td>
<td>categorical</td>
<td>the <em>rate of probability</em> of being in each of the output categories per unit of change in the input.</td>
</tr>
</tbody>
</table>
<p>Terms like “rate of probability” can be confusingly abstract. It helps to have some examples in mind to keep your thinking clear.</p>
<p>Examples:</p>
<ul>
<li>System: an automobile
<ul>
<li>Selected input: Gallons of gasoline put in a car’s tank. Quantitative.</li>
<li>Selected output: How far the car can be driven.</li>
<li>Effect size will be a <em>rate</em>: miles per gallon.</li>
</ul></li>
<li>System: an autombile
<ul>
<li>Selected input: Whether to use a fuel additive the promises high fuel efficiency. Categorical.</li>
<li>Selected output: Money spent on fuel (or, perhaps, tons of CO_2 emitted). Quantitative.</li>
<li>Effect size is an <em>amount</em>: Dollars spent (or, tons of CO_2 emitted)</li>
</ul></li>
<li>System:
<ul>
<li>input categorical</li>
<li>output quantitative</li>
</ul></li>
<li>System:
<ul>
<li>input categorical</li>
<li>output quantitative</li>
</ul></li>
</ul>
</section>
<section id="calculating-an-effect-size" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="calculating-an-effect-size">Calculating an effect size</h2>
<p>So long as you keep track of which of the four combinations of input and out are applicable to your case, calculating an effect size is easy. You evaluate the model at two values for the input then collect the two corresponding output values. For instance, you can use the <code>model_eval()</code> function. It takes as arguments the model whose effect size you’re interested in and, optionally, values for some or all of the inputs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp, <span class="at">data=</span>mtcars)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model_eval</span>(Mod, <span class="at">hp=</span><span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">150</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   hp  .output     .lwr     .upr
1 100 23.27603 15.20660 31.34547
2 150 19.86462 11.85278 27.87645</code></pre>
</div>
</div>
<p>The column labeled <code>.output</code> shows the model output for the corresponding input values for <code>hp</code>. Here, both the input and the output are quantitative, so the effect size will be a ratio: change in output divided by change in input. In this case: <span class="math display">\[\text{effect size:}\ \ \frac{23.28-19.86}{100-150} = -0.0684\]</span> It is wise to pay attention to the <em>units</em> of the effect size. Here, the output is <code>mpg</code>, which has units miles-per-gallon. The input has units horsepower, so the units of the effect size are miles gallon<sup>-1</sup> horsepower<sup>-1</sup>. Admittedly, that’s a mouthful of units. But it tells us something simple: A car with 100 additional horsepower will get worse fuel economy, down by 6.8 miles per gallon.</p>
<p>Notice that the report from <code>model_eval()</code> has additional columns: <code>.lwr</code> and <code>.upr</code>. That s a glue that it is giving both a single-number, “point” estimate (<code>.output.</code>) and a two number interval estimate. We’ll talk about the meaning of the interval in the following section and in Lesson 26.</p>
<div class="callout-warning callout callout-style-default callout-captioned page-columns page-full">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Is horsepower the cause?
</div>
</div>
<div class="callout-body-container callout-body page-columns page-full">
<p>It might seem from the negative sign on the effect size of engine horsepower on fuel economy that a more powerful engine is not as efficient than a less powerful engine at moving the car a given number of miles. That’s a reasonable conclusion. But the statistical thinker always keeps in mind other possibilities. For instance, another factor in fuel economy is the overall weight of the vehicle. A van designed to haul many passengers weighs more than a 2-passenger sporty vehicle. The van needs more horsepower because it is accelerating more weight.</p>
<div class="cell">

</div>
<p><a href="#fig-four-hp-mpg-dags">Figure&nbsp;1</a> shows four DAGs, each of which describe a plausible scenario.</p>
<div class="page-columns page-full">
<div id="fig-four-hp-mpg-dags" class="cell column-page-right quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 25.0%;justify-content: center;">
<div id="fig-four-hp-mpg-dags-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-24_files/figure-html/fig-four-hp-mpg-dags-1.png" class="img-fluid figure-img" data-ref-parent="fig-four-hp-mpg-dags"></p>
<p></p><figcaption class="figure-caption">(a) Dag A</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 25.0%;justify-content: center;">
<div id="fig-four-hp-mpg-dags-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-24_files/figure-html/fig-four-hp-mpg-dags-2.png" class="img-fluid figure-img" data-ref-parent="fig-four-hp-mpg-dags"></p>
<p></p><figcaption class="figure-caption">(b) Dag B</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 25.0%;justify-content: center;">
<div id="fig-four-hp-mpg-dags-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-24_files/figure-html/fig-four-hp-mpg-dags-3.png" class="img-fluid figure-img" data-ref-parent="fig-four-hp-mpg-dags"></p>
<p></p><figcaption class="figure-caption">(c) Dag C</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 25.0%;justify-content: center;">
<div id="fig-four-hp-mpg-dags-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-24_files/figure-html/fig-four-hp-mpg-dags-4.png" class="img-fluid figure-img" data-ref-parent="fig-four-hp-mpg-dags"></p>
<p></p><figcaption class="figure-caption">(d) Dag D</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Scenarios for the relationship between automobile fuel economy, weight, and horsepower</figcaption><p></p>
</figure>
</div>
</div>
<p>In DAG A, the vehicle’s design weight determines that an engine with high horsepower will be part of the design. The weight is also responsible for the lower fuel economy.</p>
<p>The other DAGs describe other scenarios. In DAG C, for instance, the car designers decided to build a muscle car and put in a big engine. The engine itself adds to the vehicle’s weight, and the higher weight determines lower miles per gallon. DAG D expresses a slightly different belief: again the choice to build a muscle car (high <code>hp</code>) influences the weight. But in DAG B, the big engine also directly influences the fuel economy, perhaps because the fuel-to-air ratio of the car, in normal use, is not optimal.</p>
<p>As we will see in Lesson 28, to reveal the direct causal link between engine power and fuel economy requires different choices for the model formula depending on which DAG you think might be relevant.</p>
</div>
</div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example for LCs: Price of book versus its page count.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Another example: Are longer books more expensive? Intuition suggests so, because more editing, paper, printing and shipping goes into making a longer book. We have some data that might be informative, <code>moderndive::amazon_books</code>. We can build a model of, say, <code>list_price</code> versus <code>num_pages</code>. To look at the effect size, let’s compare a 200-page book to a 400-page book.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> num_pages, <span class="at">data =</span> moderndive<span class="sc">::</span>amazon_books)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model_eval</span>(Mod, <span class="at">num_pages =</span> <span class="fu">c</span>(<span class="dv">200</span>, <span class="dv">400</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  num_pages  .output       .lwr     .upr
1       200 15.82014 -11.636987 43.27726
2       400 19.79643  -7.637503 47.23037</code></pre>
</div>
</div>
<p>The longer book costs about 4 dollars more. So the effect size, to judge from this model, is $4 dollars divided by 200 more pages, which comes to 2 cents per page.</p>
</div>
</div>
<p>Another example: Are hardcovers more expensive than paperbacks? The output is a quantitative variable: price. The input is categorical. In the <code>moderndive::amazon_books</code> data frame the variable <code>hard_paper</code> has levels “P” and “H.” A possible model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> hard_paper, <span class="at">data =</span> amazon_books)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model_eval</span>(Mod, <span class="at">hard_paper =</span> <span class="fu">c</span>(<span class="st">"P"</span>, <span class="st">"H"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  hard_paper  .output      .lwr     .upr
1          P 17.13523 -10.62291 44.89338
2          H 22.39393  -5.46052 50.24839</code></pre>
</div>
</div>
</section>
<section id="multiple-explanatory-variables" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="multiple-explanatory-variables">Multiple explanatory variables</h2>
<p>When a model has more than one explanatory variable, there is a separate effect size for each. To illustrate, let’s consider prices of houses as recorded in the <code>mosaicData::SaratogaHouses</code> data frame, based on house sales in Saratoga County, NY, USA in 2006. We’ll follow a question asked by then-student Candice Corvetti in her Stat 101 class at Williams College: “How much is a fireplace worth?” Response variable: <code>price</code>. Explanatory variable: <code>fireplaces</code>. Since a handful of the houses has multiple fireplaces, we will simplify by filtering out those houses to retain only the ones with a single fireplace or none.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Simplified <span class="ot">&lt;-</span> SaratogaHouses <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fireplaces <span class="sc">&lt;=</span> <span class="dv">1</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>Mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> fireplaces, <span class="at">data =</span> Simplified)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>Mod_values <span class="ot">&lt;-</span> <span class="fu">model_eval</span>(Mod, <span class="at">fireplaces =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>Mod_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  fireplaces  .output       .lwr     .upr
1          0 174653.3  -751.4332 350058.1
2          1 235162.9 59783.5404 410542.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Simplified <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>fireplaces, <span class="at">y =</span> price)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data=</span>Mod_values, <span class="fu">aes</span>(<span class="at">ymin=</span>.output, <span class="at">ymax=</span>.output, <span class="at">x =</span> fireplaces), <span class="at">y=</span><span class="cn">NA</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">color=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Reading-notes-lesson-24_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the graphic, you can see that houses with a fireplace tend to have higher prices. From the report of the evaluated model, you can calculate the effect size: $235K for a house with a fireplace, $175K for a house without one. This suggests the value of a fireplace is $60K.</p>
<p>There are, of course, many other things that determine the price of a house. Real-estate agents famously list the three most important factors as “location, location, and location.” Common sense brings in other explanatory variables: how big the house is, how luxurious, how many bathrooms, and so on. The statistical thinker knows to put any one explanatory variable into the context of other plausable factors.</p>
<p>For simplicity, let’s collect all the factors other than <code>fireplaces</code> into a hypothetical variable which we will call “<code>fancy</code>.” Here are three plausible DAGs that plausibly describe an affect of fireplace on <code>price</code> in the context of <code>fancy</code>.</p>
<div class="page-columns page-full">
<div id="fig-fireplace-dags" class="cell column-page-right quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fireplace-dags-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-24_files/figure-html/fig-fireplace-dags-1.png" class="img-fluid figure-img" data-ref-parent="fig-fireplace-dags"></p>
<p></p><figcaption class="figure-caption">(a) Dag A</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fireplace-dags-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-24_files/figure-html/fig-fireplace-dags-2.png" class="img-fluid figure-img" data-ref-parent="fig-fireplace-dags"></p>
<p></p><figcaption class="figure-caption">(b) Dag B</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fireplace-dags-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-24_files/figure-html/fig-fireplace-dags-3.png" class="img-fluid figure-img" data-ref-parent="fig-fireplace-dags"></p>
<p></p><figcaption class="figure-caption">(c) Dag C</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Scenarios relating the price of a house to having a fireplace</figcaption><p></p>
</figure>
</div>
</div>
<p>In DAG A, <code>fancy</code> and <code>fireplace</code> both contribute to <code>price</code>, but independently. In DAG B, <code>fireplace</code> directly contributes to <code>price</code>, but whether or not a house has a fireplace depends on the level of <code>fancy</code>. In DAG D, <code>fireplace</code> has no direct affect on <code>price</code>, which is set entirely by <code>fancy</code>. The <code>fireplace</code> variable is just an indicator of <code>fancy</code>.</p>
<p>We can’t say from the data alone which of these three DAGs is the closest description of the situation. In Lessons 28, 30, and 31 we will consider how the choice of explanatory variables in a model leads to a faithful or misleading picture of the connections. There you will find out that DAGS A &amp; B both imply that <code>fancy</code> should be an explanatory variable if we want the effect size from the model to represent the <strong>direct</strong> effect of a fireplace on price. Easy enough to fit that model, … except that we don’t have an actual variable <code>fancy</code> in the <code>SaratogaHouses</code> data frame. To keep things simple for the moment, we will use <code>livingArea</code>—the size of the house—as a rough approximation to the hypothetical <code>fancy</code>.</p>
<p>The effect size of <code>fireplaces</code> on <code>price</code> is found by comparing the model output for houses with and without a fireplace, <em>holding the values of all the other explanatory variables</em> <strong>constant</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> fireplaces <span class="sc">+</span> livingArea, <span class="at">data =</span> Simplified)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model_eval</span>(Mod2, <span class="at">fireplaces =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">livingArea =</span> <span class="dv">2000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  fireplaces livingArea  .output     .lwr     .upr
1          0       2000 234706.4 101212.9 368199.9
2          1       2000 240420.8 106988.7 373852.8</code></pre>
</div>
</div>
<p>For a house with living area 2000 feet<sup>2</sup>, the model output is $235K with no fireplace and $240K with a fireplace, putting the effect size of <code>fireplace</code> on <code>price</code> at $5K. That’s much smaller than the previous model, <code>price ~ fireplace</code>, gave for the effect size. The reason for the difference in results from the two models is that houses with fireplaces tend to be larger in area.</p>
</section>
<section id="confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals">Confidence intervals</h2>
<p>Statistical thinkers know that any estimate they make, including estimates of effect sizes, are subject to sampling variation. Consequently, an <em>interval</em> estimate should be given. This communicates to the decision maker the uncertainty in the quantity being estimated. Sophisticated decision makes take this uncertainty into account, considering the range of outcomes likely from whatever use they make of an effect size. Statistically naive decision makers—even highly educated descision makers can be statistically naive—look at the interval and will sometimes ask the modeler, “Just give me a number. I don’t know what to do with two numbers.” Such a request might elicit a frank response: “If you don’t know what to do with two numbers, you also won’t know what to do with one number.” That kind of frankness is not often well received; a reasonable alternative is: “The interval indicates the amount of uncertainty in the result. If you would like to reduce the uncertainty, we’ll need to collect more data.” (In Lesson 29 you’ll meet a not-always-available alternative to collecting more data: building a better model!)</p>
<p>The appropriate interval estimate for an effect size is called a “<strong>confidence interval</strong>.” It’s extremely important to keep this name in mind, since there is another kind of interval to quantify uncertainty, called a “prediction interval,” which will be introduced in Lesson’s 25 and 26. Confusing the two kinds of intervals is a serious blunder.</p>
<p>Confidence interval can be constructed using the same sorts of techniques introduced in Lesson 23. For models that are constructed by adding together different terms, like the <code>price ~ fireplaces + livingArea</code> model of the previous example, the estimated effect size for a given term is the corresponding model coefficient. The confidence interval on that effect size is simply the confidence interval on the coefficient. For example, for fireplaces:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(price <span class="sc">~</span> fireplaces <span class="sc">+</span> livingArea, <span class="at">data =</span> Simplified) <span class="sc">%&gt;%</span> <span class="fu">confint</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept)  6979.0960 27188.993
fireplaces  -1521.3683 12950.131
livingArea    102.7093   114.913</code></pre>
</div>
</div>
<p>Thus, the confidence interval for the effect of a fireplace ranges from negative $1500 to positive $13,000. Broad though this may seem at first, it does carry genuine information. You can be confident that a fireplace alone will not add as much as $50,000 to the price of the house, nor will it cause the house’s value to fall by $10,000.</p>
<p>The confidence interval on the <code>livingArea</code> is pretty narrow $103 to $115 per square foot. If you’re looking to save a bit of money by shopping for a slighly smaller house, say 200 square-feet smaller, you can adjust your budget downwards by something in the range of $206,000 to $230,000. The units here come from multiplying the area units (square feet) by the effect size units (dollars per square feet), producing a quantity denominated in dollars.</p>
<p>It’s important always to keep in mind that an estimate of an effect size will likely be misleading if your choice of model seriously misrepresents reality. For instance, a salesperson hawking add-on fireplaces might show you results from the “obvious” model <code>price ~ fireplace</code>, leading to an effect size of $52,000 to $69,000, calculated this way.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(price <span class="sc">~</span> fireplaces, <span class="at">data =</span> Simplified) <span class="sc">%&gt;%</span> <span class="fu">confint</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 168209.69 181097.01
fireplaces   51899.26  69119.92</code></pre>
</div>
</div>
<p>It would be unfair to say that the $52,000 to $69,000 claim is a lie; it’s entirely consistent with the data. But it relies on a grossly implausible description of the factors that determine house price.</p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note in draft: For the confounding section
</div>
</div>
<div class="callout-body-container callout-body">
<p>An idea …</p>
<p>Suppose the DAG is that fireplaces cause living area (<code>fancy</code>) and that both of these cause price. That’s distinct from DAG C in the above, because the causal arrow from <code>fancy</code> to <code>fireplace</code> is reversed. Could we decide between DAG C and this new DAG. How about the models <code>fireplace ~ livingArea</code> versus <code>fireplace</code> versus <code>fancy</code> plus <code>price</code>.</p>
</div>
</div>
</section>
<section id="interaction" class="level2">
<h2 class="anchored" data-anchor-id="interaction">Interaction</h2>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note in draft:
</div>
</div>
<div class="callout-body-container callout-body">
<p>Not all effects are additive.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>