<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lessons in Statistical Thinking - 29&nbsp; Covariates eat variance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Reading-notes-lesson-30.html" rel="next">
<link href="./Reading-notes-lesson-28.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Covariates eat variance</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Lessons in Statistical Thinking</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">1-18 from ModernDive</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bogus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bogus</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Lessons in Statistical Thinking</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-19.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Preliminaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-20.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Measuring and simulating variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-21.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Signal and noise</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-22.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Sampling and sampling variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-23.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Estimating sampling variation from a single sample</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-24.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Effect size: Input to output</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-25.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Mechanics of prediction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-26.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Constructing a prediction interval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./QR1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Review of Lessons 1-8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-28.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Covariates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-29.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Covariates eat variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-30.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Confounding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-31.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Spurious correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-32.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Experiment and random assignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-33.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Measuring and accumulating risk</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-34.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Constructing a classifier</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-35.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Accounting for prevalence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-36.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-37.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Calculating a p-value</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reading-notes-lesson-38.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">False discovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./QR2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Review of Lessons 9-19</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#how-much-variation-is-explained" id="toc-how-much-variation-is-explained" class="nav-link active" data-scroll-target="#how-much-variation-is-explained">How much variation is explained</a></li>
  <li><a href="#getting-to-1" id="toc-getting-to-1" class="nav-link" data-scroll-target="#getting-to-1">Getting to 1</a></li>
  <li><a href="#the-isbn-effect-as-a-benchmark" id="toc-the-isbn-effect-as-a-benchmark" class="nav-link" data-scroll-target="#the-isbn-effect-as-a-benchmark">The ISBN effect as a benchmark</a></li>
  <li><a href="#the-f-statistic" id="toc-the-f-statistic" class="nav-link" data-scroll-target="#the-f-statistic">The F statistic</a></li>
  <li><a href="#comparing-models" id="toc-comparing-models" class="nav-link" data-scroll-target="#comparing-models">Comparing models</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Covariates eat variance</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In Lesson 28, we introduced covariates to set the relationship between an explanatory variable and the response variable in the correct context. In Lesson 30, we will return to this context-setting role to show that the appropriate choice of covariates to include in a model depends on the modeler’s opinion about the relevant structure of a DAG. Here, we will treat covariates as commodity items to show a surprising property of models. This property is a boon to the modeler, helping to enable sound decisions about whether to include any given covariate. However, it is also a pitfall lieing in wait for the wishful thinker.</p>
<section id="how-much-variation-is-explained" class="level2">
<h2 class="anchored" data-anchor-id="how-much-variation-is-explained">How much variation is explained</h2>
<p>We start by returning to the definition of statistical thinking introduced at the start of these Lessons:</p>
<blockquote class="blockquote">
<p><em>Statistic thinking is the explanation or description of variation</em> in the context of <em>what remains unexplained or undescribed.</em></p>
</blockquote>
<p>In this Lesson, we will work with a straightforward measure of “what remains unexplained or undescribed.” The fitted model values represent the explained part of the variation. The residuals are what is left over, the difference between the actual values of the response variable and the fitted model values.</p>
<p>As a reminder, we will construct a simple model of the list price of books as a function of the number of pages and whether the book is a paperback or hardcover.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Price_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> num_pages <span class="sc">+</span> hard_paper, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> amazon_books)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>model_eval()</code> function can extract the fitted model values and the residuals from the model. We show just a few rows here, but we will use the entire report from <code>model_eval()</code>. Remember that when <code>model_eval()</code> is not given input values, it uses the model <em>training</em> data as input.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Results <span class="ot">&lt;-</span> <span class="fu">model_eval</span>(Price_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> list_price </th>
   <th style="text-align:right;"> num_pages </th>
   <th style="text-align:left;"> hard_paper </th>
   <th style="text-align:right;"> .output </th>
   <th style="text-align:right;"> .resid </th>
   <th style="text-align:right;"> .lwr </th>
   <th style="text-align:right;"> .upr </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 12.95 </td>
   <td style="text-align:right;"> 304 </td>
   <td style="text-align:left;"> P </td>
   <td style="text-align:right;"> 16.60 </td>
   <td style="text-align:right;"> -3.65 </td>
   <td style="text-align:right;"> -10.73 </td>
   <td style="text-align:right;"> 43.94 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 15.00 </td>
   <td style="text-align:right;"> 273 </td>
   <td style="text-align:left;"> P </td>
   <td style="text-align:right;"> 15.98 </td>
   <td style="text-align:right;"> -0.98 </td>
   <td style="text-align:right;"> -11.36 </td>
   <td style="text-align:right;"> 43.32 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1.50 </td>
   <td style="text-align:right;"> 96 </td>
   <td style="text-align:left;"> P </td>
   <td style="text-align:right;"> 12.45 </td>
   <td style="text-align:right;"> -10.95 </td>
   <td style="text-align:right;"> -14.97 </td>
   <td style="text-align:right;"> 39.88 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 15.99 </td>
   <td style="text-align:right;"> 672 </td>
   <td style="text-align:left;"> P </td>
   <td style="text-align:right;"> 23.95 </td>
   <td style="text-align:right;"> -7.96 </td>
   <td style="text-align:right;"> -3.57 </td>
   <td style="text-align:right;"> 51.47 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 30.50 </td>
   <td style="text-align:right;"> 720 </td>
   <td style="text-align:left;"> P </td>
   <td style="text-align:right;"> 24.91 </td>
   <td style="text-align:right;"> 5.59 </td>
   <td style="text-align:right;"> -2.67 </td>
   <td style="text-align:right;"> 52.49 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 28.95 </td>
   <td style="text-align:right;"> 460 </td>
   <td style="text-align:left;"> H </td>
   <td style="text-align:right;"> 24.57 </td>
   <td style="text-align:right;"> 4.38 </td>
   <td style="text-align:right;"> -2.89 </td>
   <td style="text-align:right;"> 52.03 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The first book in the training data is a 304-page paperback with a list price of $12.95. The fitted model value for that book is $16.60. (Ordinarily, we refer to the output of the model function simply as the “output” or the “model output.” However, the output of the model function, when applied to rows from the <em>training</em> data also called the <em>fitted model value</em>.)</p>
<p>At $16.60, the fitted model value is $3.65 <em>higher</em> than the list price. This difference is the residual for that book, the sign reflecting the definition <span class="math display">\[\text{residual} \equiv \text{response value} - \text{fitted model value}\ .\]</span> When the residual is small in magnitude, the fitted model value is close to the response value. Conversely, a large residual means the model was way off target for that book.</p>
<p>The standard measure of the typical size of a residual is the standard deviation or, equivalently, the variance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Results <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">se_resids =</span> <span class="fu">sd</span>(.resid), <span class="at">v_resids=</span><span class="fu">var</span>(.resid))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  se_resids v_resids
1  13.81885 190.9606</code></pre>
</div>
</div>
<p>As always, the standard deviation is easier to read because it has sensible units, in this case, dollars. On the other hand, the variance has strange units (square dollars) because it is the square of the standard deviation. We will use the variance for measuring the typical size of a residual for the reasons described in Lesson 20; variances add nicely in a manner analogous to the Pythagorean Theorem.</p>
<p>Similarly, the total amount of variation in the list price is simply the variance of the list price:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Results <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">v_response =</span> <span class="fu">var</span>(list_price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  v_response
1   206.5129</code></pre>
</div>
</div>
<p>A simple measure of how much of the variation in list price remains unexplained is the ratio of these variances <span class="math inline">\(190.96/206.51 = 92.5\%\)</span>. More than 90% of the variation remains unexplained by the <code>Price_model</code>. This high fraction of unexplained variance suggests the model has little to tell us. In the spirit of putting a positive spin on things, statisticians typically work with the complement of the unexplained fraction. Since the unexplained fraction is 92.5%, the complement is 7.5%. This number is written R<sup>2</sup> and pronounced “R-squared.” (It also has a formal name: the “coefficient of determination.” In Lesson 30, we will meet the inventor of the coefficient of determination, Sewall Wright, who is an early hero of causal reasoning.)</p>
<p>R<sup>2</sup> is such a widely used summary of how the explanatory variables account for the response variable that a software extractor calculates it and some related values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Price_model <span class="sc">%&gt;%</span> <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n k   Rsquared        F      adjR2
1 317 2 0.07530934 12.78651 0.06941959</code></pre>
</div>
</div>
<p>Many modelers act as if their goal is to build a model that makes R<sup>2</sup> as big as possible. Their thinking is that large R<sup>2</sup> means that the explanatory variables account for much of the response variable’s variance. Unfortunately, it is a naive goal. Instead, always focus on the model’s suitability for the purpose at hand. Often, shooting for a large R<sup>2</sup> imposes costs that can undermine the purpose for the model. Furthermore, even models with the largest possible R<sup>2</sup> sometimes have nothing to say about the response variable.</p>
</section>
<section id="getting-to-1" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="getting-to-1">Getting to 1</h2>
<p>R<sup>2</sup> can range from zero to one. Zero means that the model accounts for <em>none</em> of the variation in the response variable. We can construct such a model quickly enough: <code>list_price ~ 1</code> has no explanatory variables and, therefore, no ability to distinguish one book from another.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> amazon_books)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>Null_model <span class="sc">%&gt;%</span> <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n k Rsquared   F adjR2
1 319 0        0 NaN     0</code></pre>
</div>
</div>
<p>We are using the word “null” to name this model. “Null” is part of the statistics tradition. The dictionary definition of “null” is “having or associated with the value zero” or “lacking distinctive qualities; having no positive substance or content.”<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>In the null model, the fitted model values are all the same; all the variation is in the residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Null_model <span class="sc">%&gt;%</span> <span class="fu">model_eval</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> list_price </th>
   <th style="text-align:right;"> .output </th>
   <th style="text-align:right;"> .resid </th>
   <th style="text-align:right;"> .lwr </th>
   <th style="text-align:right;"> .upr </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 12.95 </td>
   <td style="text-align:right;"> 18.6 </td>
   <td style="text-align:right;"> -5.65 </td>
   <td style="text-align:right;"> -9.69 </td>
   <td style="text-align:right;"> 46.89 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 15.00 </td>
   <td style="text-align:right;"> 18.6 </td>
   <td style="text-align:right;"> -3.60 </td>
   <td style="text-align:right;"> -9.69 </td>
   <td style="text-align:right;"> 46.89 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1.50 </td>
   <td style="text-align:right;"> 18.6 </td>
   <td style="text-align:right;"> -17.10 </td>
   <td style="text-align:right;"> -9.69 </td>
   <td style="text-align:right;"> 46.89 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 15.99 </td>
   <td style="text-align:right;"> 18.6 </td>
   <td style="text-align:right;"> -2.61 </td>
   <td style="text-align:right;"> -9.69 </td>
   <td style="text-align:right;"> 46.89 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 30.50 </td>
   <td style="text-align:right;"> 18.6 </td>
   <td style="text-align:right;"> 11.90 </td>
   <td style="text-align:right;"> -9.69 </td>
   <td style="text-align:right;"> 46.89 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 28.95 </td>
   <td style="text-align:right;"> 18.6 </td>
   <td style="text-align:right;"> 10.35 </td>
   <td style="text-align:right;"> -9.69 </td>
   <td style="text-align:right;"> 46.89 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>At the other extreme, where R<sup>2</sup> = 1, the explanatory variables account for every bit of variation in the response variable. We can try various combinations of explanatory variables to see if we can accomplish this. For example, <code>publisher</code> explains 67% of the variation in list price.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(list_price <span class="sc">~</span> publisher, <span class="at">data =</span> amazon_books) <span class="sc">%&gt;%</span> <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n   k  Rsquared        F     adjR2
1 319 158 0.6749786 2.103008 0.3540199</code></pre>
</div>
</div>
<p>We can also check whether <code>author</code> has anything to say about the list price.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(list_price <span class="sc">~</span> author, <span class="at">data =</span> amazon_books) <span class="sc">%&gt;%</span> <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n   k  Rsquared        F     adjR2
1 319 250 0.9434046 4.534044 0.7353333</code></pre>
</div>
</div>
<p>Incredible! How about if we use <em>both</em> <code>publisher</code> and <code>author</code> as explanatory variables? We get very close to R<sup>2</sup> = 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(list_price <span class="sc">~</span> publisher <span class="sc">+</span> author, <span class="at">data =</span> amazon_books) <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n   k  Rsquared        F   adjR2
1 319 281 0.9821609 7.249441 0.84668</code></pre>
</div>
</div>
<p>The modeler discovering this tremendous explanatory power of <code>publisher</code> and <code>author</code> can be forgiven for thinking he or she has found a meaningful explanation. But, unfortunately, the high R<sup>2</sup> is an illusion in this case.</p>
<p>To see why, consider another possible explanatory variable, the International Standard Book Number (ISBN). The ISBN is a ten- or thirteen-digit number that marks each book with a unique number.</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"www/SM2-ISBN.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div id="fig-isbn-sm2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="www/SM2-ISBN.png" class="img-fluid figure-img" width="241"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;29.1: The ISBN number from one of the Project MOSAIC textbooks.</figcaption><p></p>
</figure>
</div>
</div></div></div>
<p>There is a system behind ISBNs, but despite the “N” standing for “number,” an ISBN is a character string or word (written using only digits). Consequently, the <code>isbn_10</code> variable in <code>amazon_books</code>is categorical.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ISBN_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> isbn_10, <span class="at">data =</span> amazon_books)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>ISBN_model <span class="sc">%&gt;%</span> <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n   k Rsquared   F adjR2
1 319 318        1 NaN   NaN</code></pre>
</div>
</div>
<p>The <code>isbn_10</code> explains all variation in the list price!</p>
<p>Given that the ISBN is, as we have said, an arbitrary sequence of characters, why does it do such a good job of accounting for the list price? The answer lies not in the content of the ISBN but in another fact: each book has a unique ISBN. As well, each book has a single price. So the ISBN identifies the price of each book. Cleverness is not involved; the list price could be anything, and the ISBN would still identify it precisely. The model coefficients store the whole set of ISBNs and the corresponding set of list prices.</p>
<p>We can substantiate the claim just made—that the list price could be anything at all—by synthesizing a data frame with random list prices:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>amazon_books <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">random_list_price =</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(.))) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(random_list_price <span class="sc">~</span> isbn_10, <span class="at">data =</span> .) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n   k Rsquared   F adjR2
1 319 318        1 NaN   NaN</code></pre>
</div>
</div>
<p>Similar randomization can be accomplished by <em>shuffling</em> the <code>isbn_10</code> column of the data frame so that each ISBN points to a random book. Of course, such shuffling destroys the link between the ISBN and the list price. Even so, the R<sup>2</sup> remains high.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(list_price <span class="sc">~</span> <span class="fu">shuffle</span>(isbn_10), <span class="at">data=</span>amazon_books) <span class="sc">%&gt;%</span> <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n   k Rsquared   F adjR2
1 319 318        1 NaN   NaN</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="fu">shuffle</span>(list_price) <span class="sc">~</span> isbn_10, <span class="at">data=</span>amazon_books) <span class="sc">%&gt;%</span> <span class="fu">R2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n   k Rsquared   F adjR2
1 319 318        1 NaN   NaN</code></pre>
</div>
</div>
<p>Statistical nomenclature is obscure here. So we will make up a name for such incidental alignment with no true explanatory power: the “<strong>ISBN-effect</strong>.”</p>
<p>Statistical thinkers know to be aware of situations where categorical variables have many levels and check whether the ISBN effect is in play.</p>
</section>
<section id="the-isbn-effect-as-a-benchmark" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="the-isbn-effect-as-a-benchmark">The ISBN effect as a benchmark</h2>
<p>Shuffling an explanatory variable (while keeping the response variable in the original order) voids any possible explanatory connection between the two. An R<sup>2</sup>=0, as we get from any model of the form <code>y ~ 1</code>, signals that the <code>1</code> cannot account for any variation. However, this does not mean shuffling will lead to R<sup>2</sup> = 0. Instead, there is a systematic relationship between the number of model coefficients associated with the shuffled variable, the sample size <span class="math inline">\(n\)</span>, and R<sup>2</sup>.</p>
<p>We can demonstrate this relationship by conducting many trials of modeling the <code>list_price</code> with a shuffled explanatory variable: either <code>publisher</code>, <code>author</code>, or <code>isbn_10</code>.</p>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Demonstration: Counting coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>amazon_books</code> data frame has <span class="math inline">\(n=319\)</span> rows.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> In the next computing chunk, we fit the model <code>list_price ~ publisher</code> and collect the coefficients for counting:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>Publisher_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> <span class="fu">shuffle</span>(publisher),</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data=</span>amazon_books)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>Coefficients <span class="ot">&lt;-</span> Publisher_model <span class="sc">%&gt;%</span> <span class="fu">coefficients</span>() <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(Coefficients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 159</code></pre>
</div>
</div>
<p>There are 159 coefficients in the model, the first one being the “Intercept.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>Coefficients <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<p>Altogether, there are <span class="math inline">\(k=158\)</span> coefficients relating to <code>shuffle(publisher)</code>.</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div class="cell-output-display callout-margin-content">
<div id="tbl-shuffle-publisher" class="anchored">

<table><caption>Table&nbsp;29.1:  Confidence intervals on the first six of 161 coefficients in list_price ~ publisher </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:right;"> 14.95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> shuffle(publisher)Adams Media </td>
   <td style="text-align:right;"> 0.05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> shuffle(publisher)Akashic Books </td>
   <td style="text-align:right;"> 13.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> shuffle(publisher)Aladdin </td>
   <td style="text-align:right;"> 15.05 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> shuffle(publisher)Albert Whitman &amp; Company </td>
   <td style="text-align:right;"> -0.95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> shuffle(publisher)Alfred A. Knopf </td>
   <td style="text-align:right;"> 0.05 </td>
  </tr>
</tbody>
</table>

</div>
</div></div><p>The rule relating R<sup>2</sup> to the number of coefficients associated is straightforward for shuffled explanatory variables: R<sup>2</sup> will be random with mean value <span class="math inline">\(\frac{k}{n-1}\)</span>. For the <code>shuffle(publisher)</code> model, the mean across many trials will be R<sup>2</sup> = 158/324 = 0.49.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>Pub_trials <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100</span>) <span class="sc">*</span> {</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(list_price <span class="sc">~</span> <span class="fu">shuffle</span>(publisher), <span class="at">data=</span>amazon_books) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">R2</span>()</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell page-columns page-full">

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div id="fig-pub-trials" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-29_files/figure-html/fig-pub-trials-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;29.2: 100 trials of R<sup>2</sup> from <code>list_price ~ shuffled(publisher)</code>. The theoretical value <span class="math inline">\(k/n=160/324=0.49\)</span> is marked in red.</figcaption><p></p>
</figure>
</div>
</div></div></div>
<p>:::</p>
<p>We can carry out similar trials for the models <code>list_price ~ shuffle(author)</code> and <code>list_price ~ shuffle(isbn_10)</code>, which have <span class="math inline">\(k=251\)</span> and <span class="math inline">\(k=319\)</span> respectively.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-amazon-book-shuffle" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Reading-notes-lesson-29_files/figure-html/fig-amazon-book-shuffle-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;29.3: R<sup>2</sup> from many trials of three models, <code>list_price ~ shuffle(publisher)</code> and <code>~ shuffle(author)</code> and <code>~shuffle(isbn_10)</code>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The blue diagonal line in <a href="#fig-amazon-book-shuffle">Figure&nbsp;<span>29.3</span></a> shows the theoretical average R<sup>2</sup> as a function of the number of model coefficients when the explanatory variable is randomized. R<sup>2</sup> will always be 1.0 when <span class="math inline">\(k=n\)</span>, that is, when the number of coefficients is the same as the sample size.</p>
<p><a href="#fig-amazon-book-shuffle">Figure&nbsp;<span>29.3</span></a> suggests a way to distinguish between R<sup>2</sup> resulting from the ISBN-effect and R<sup>2</sup> that shows some true explanatory power: Check if R<sup>2</sup> is substantially above the blue diagonal line, that is, check if R<sup>2</sup><span class="math inline">\(\gg \frac{k}{n-1}\)</span> where <span class="math inline">\(k\)</span> is the number of model coefficients.</p>
</section>
<section id="the-f-statistic" class="level2">
<h2 class="anchored" data-anchor-id="the-f-statistic">The F statistic</h2>
<p><span class="math inline">\(k\)</span> and <span class="math inline">\(n\)</span> provide the necessary context for proper interpretation of R<sup>2</sup>; all three numbers are needed to establish whether R<sup>2</sup> <span class="math inline">\(\gg \frac{k}{n-1}\)</span> to rule out the ISBN effect. The calculation is not difficult; the modeler always knows the size <span class="math inline">\(n\)</span> of the training data and can find <span class="math inline">\(k\)</span> as the number of coefficients in the model (not counting the Intercept term).</p>
<p>Perhaps a little easier than interpreting R<sup>2</sup> is the interpretation of another statistic, named F, which folds in the <span class="math inline">\(k\)</span>, <span class="math inline">\(n\)</span>, and R<sup>2</sup> into a single number: <span class="math display">\[F \equiv \frac{n-k-1}{k} \frac{\text{R}^2}{1 - \text{R}^2}\]</span> <span class="quarto-unresolved-ref">?fig-amazon-book-shuffle-F</span> is a remake of <a href="#fig-amazon-book-shuffle">Figure&nbsp;<span>29.3</span></a> but using F instead of R<sup>2</sup>. The blue line, which had the formula R<sup>2</sup><span class="math inline">\(= k/(n-1)\)</span> in <a href="#fig-amazon-book-shuffle">Figure&nbsp;<span>29.3</span></a>, gets translated to the constant value 1.0 in <span class="quarto-unresolved-ref">?fig-amazon-book-shuffle-F</span>, regardless of <span class="math inline">\(k\)</span>. To decide when a model points to a connection stronger than the ISBN effect, the threshold F <span class="math inline">\(&gt; 3\)</span> is a good rule of thumb. (Lesson 37 introduces a more precise calculation for the F threshold, which is built into statistical software and presented as a “<strong>p-value</strong>.”)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>k, <span class="at">y=</span>F), <span class="at">data=</span>All_trials) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="dv">15</span>, <span class="at">alpha=</span>.<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept=</span><span class="dv">1</span>, <span class="at">slope=</span><span class="dv">0</span>), <span class="at">color=</span><span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="dv">0</span>, <span class="at">y=</span><span class="dv">0</span>), <span class="at">alpha=</span><span class="dv">0</span>) <span class="sc">+</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle=</span><span class="st">"with shuffling"</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="fu">expression</span>(F)) <span class="sc">+</span> </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">50</span>, <span class="dv">100</span>,<span class="dv">158</span>,<span class="dv">200</span>, <span class="dv">251</span>,  <span class="dv">318</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 100 rows containing missing values (geom_point).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Reading-notes-lesson-29_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Adjusted R<sup>2</sup>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Some fields, notably economics, prefer an alternative to F called “<strong>adjusted R<sup>2</sup></strong>” (or <span class="math inline">\(R^2_\text{adj}\)</span>). The adjustment comes from moving the raw R<sup>2</sup> downward and leftward, more-or-less in the direction of the blue line in <a href="#fig-amazon-book-shuffle">Figure&nbsp;<span>29.3</span></a>. This movement adjusts a raw <span class="math inline">\(R^2\)</span> that lies on the blue line to <span class="math inline">\(R^2_\text{adj} = 0\)</span>.</p>
<p>We leave the debate on the relative merits of using F or <span class="math inline">\(R^2_\text{adj}\)</span> their respective boosters. However, before getting wrapped up in such debates, it is worth pointing out that <span class="math inline">\(R^2_\text{adj}\)</span> is just a rescaling of F.</p>
<p><span class="math display">\[R^2_\text{adj} = 1 - \frac{n-1}{k} \frac{R^2}{F}\ .\]</span></p>
</div>
</div>
</section>
<section id="comparing-models" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="comparing-models">Comparing models</h2>
<p>Modelers are often in the position of having a model that they like but are contemplating adding one or more additional explanatory variables. To illustrate, consider the following models:</p>
<ul>
<li>Model 1: <code>list_price ~ 1</code></li>
<li>Model 2: <code>list_price ~ 1 + hard_paper</code></li>
<li>Model 3: <code>list_price ~ 1 + hard_paper + num_pages</code></li>
<li>Model 4: <code>list_price ~ 1 + hard_paper + num_pages + weight_oz</code></li>
</ul>
<div class="cell page-columns page-full">

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div id="fig-russian-dolls" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="www/Russian-Matroshka_no_bg.jpeg" class="img-fluid figure-img" width="230"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;29.4: Nesting Russian dolls</figcaption><p></p>
</figure>
</div>
</div></div></div>
<p>All the explanatory variables in the smaller models also apply to the bigger models. Such sets are said to be “<strong>nested</strong>” in much the same way as for Russian dolls.</p>
<p>For a nested set of models, R<sup>2</sup> can never decrease when moving from a smaller model to a larger one—almost always, there is an increase in R<sup>2</sup>. To demonstrate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>amazon_books <span class="ot">&lt;-</span> amazon_books <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(list_price, weight_oz, num_pages, hard_paper) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>amazon_books)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> weight_oz, <span class="at">data =</span> amazon_books)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> weight_oz <span class="sc">+</span> num_pages, <span class="at">data=</span>amazon_books)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(list_price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> weight_oz <span class="sc">+</span> num_pages <span class="sc">+</span> hard_paper, <span class="at">data=</span>amazon_books)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">R2</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n k Rsquared   F adjR2
1 309 0        0 NaN     0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">R2</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n k  Rsquared        F     adjR2
1 309 1 0.1558551 56.68166 0.1531055</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">R2</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n k  Rsquared        F     adjR2
1 309 2 0.1662332 30.50456 0.1607838</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">R2</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n k  Rsquared        F     adjR2
1 309 3 0.1697025 20.77941 0.1615357</code></pre>
</div>
</div>
<p>When adding explanatory variables to a model, a good question is whether the new variable(s) add to the ability to account for the variability in the response variable. R<sup>2</sup> never goes down when moving from a smaller to a larger model, so we cannot rely on the increase in R<sup>2</sup>. A valuable technique called “<strong>Analysis of Variance</strong>” (ANOVA for short) looks at the incremental change in variance explained from a smaller model to a larger one. The increase can be presented as an F statistic. To illustrate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1, model2, model3, model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: list_price ~ 1
Model 2: list_price ~ 1 + weight_oz
Model 3: list_price ~ 1 + weight_oz + num_pages
Model 4: list_price ~ 1 + weight_oz + num_pages + hard_paper
  Res.Df   RSS Df Sum of Sq       F    Pr(&gt;F)    
1    308 54531                                   
2    307 46032  1    8499.0 57.2516 4.565e-13 ***
3    306 45466  1     565.9  3.8123   0.05179 .  
4    305 45277  1     189.2  1.2744   0.25983    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Focus on the F column of the report. The move from Model 1 to Model 2 produces F=57, well above the threshold described above and clearly indicating that the <code>weight_oz</code> variable accounts for some of the list price. Moving from Model 2 to Model 3 creates a much less impressive F of 3.8. It is as if the added explanatory variable, <code>num_pages</code>, is just barely pulling its own “weight.” Finally, moving from Model 3 to Model 4 produces a below-threshold F of 1.3. In other words, in the context of <code>weight_oz</code> and <code>num_pages,</code> the <code>hard_paper</code> variable does not carry additional information about the list price.</p>
<p>The last column of the report, labeled <code>Pr(&gt;F)</code>, translates F into a universal 0 to 1 scale called a p-value. A large F produces a small p-value. The rule of thumb for reading p-values is that a value <span class="math inline">\(p &lt; 0.05\)</span> indicates that the added variable brings new information about the response variable. We will return to p-values and the controversy they have entailed in Lessons 36 through 38.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>If you seek to duplicate the results presented in this chapter, please note that we have deleted six rows from `amazon_books because the rows are either duplicates or have one of the variables missing. The deleted rows are 62, 103, 205, 211, 242, and 303.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Source: <a href="https://languages.oup.com/dictionaries/">Oxford Languages</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The data frame in the <code>moderndive</code> package has six additional rows, which we have deleted as duplicates or because of missing data.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Reading-notes-lesson-28.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Covariates</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Reading-notes-lesson-30.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Confounding</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>