project:
  type: book

book:
  title: "Lessons in Statistical Thinking"
  author: "Daniel Kaplan"
  date: "11/16/2022"
  chapters:
    - index.qmd
    - Reading-notes-lesson-19.qmd
    - Reading-notes-lesson-20.qmd
    - Reading-notes-lesson-21.qmd
    - Reading-notes-lesson-22.qmd
    - Reading-notes-lesson-23.qmd
    - Reading-notes-lesson-24.qmd
    - Reading-notes-lesson-25.qmd
    - Reading-notes-lesson-26.qmd
    - QR1.qmd
    - Reading-notes-lesson-28.qmd
    - Reading-notes-lesson-29.qmd
    - Reading-notes-lesson-30.qmd
    - Reading-notes-lesson-31.qmd
    - Reading-notes-lesson-32.qmd
    - Reading-notes-lesson-33.qmd
    - Reading-notes-lesson-34.qmd
    - Reading-notes-lesson-35.qmd
    - Reading-notes-lesson-36.qmd
    - Reading-notes-lesson-37.qmd
    - Reading-notes-lesson-38.qmd
    - QR2.qmd
    # - More-detail.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    number-offset: 18
  pdf:
    documentclass: scrreprt



