project:
  type: book
  output-dir: ../docs/Textbook

book:
  title: "Lessons in Statistical Thinking"
  author: "Daniel Kaplan"
  date: "12/01/2022"
  chapter-number: 33
  chapters:
    - index.qmd
    - part: 1-18 from ModernDive
      chapters:
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd
      - bogus.qmd

    - part: Lessons in Statistical Thinking
      chapters:
        - Reading-notes-lesson-19.qmd
        - Reading-notes-lesson-20.qmd
        - Reading-notes-lesson-21.qmd
        - Reading-notes-lesson-22.qmd
        - Reading-notes-lesson-23.qmd
        - Reading-notes-lesson-24.qmd
        - Reading-notes-lesson-25.qmd
        - Reading-notes-lesson-26.qmd
        - QR1.qmd
        - Reading-notes-lesson-28.qmd
        - Reading-notes-lesson-29.qmd
        - Reading-notes-lesson-30.qmd
        - Reading-notes-lesson-31.qmd
        - Reading-notes-lesson-32.qmd
        - Reading-notes-lesson-33.qmd
        - Reading-notes-lesson-34.qmd
        - Reading-notes-lesson-35.qmd
        - Reading-notes-lesson-36.qmd
        - Reading-notes-lesson-37.qmd
        - Reading-notes-lesson-38.qmd
        - QR2.qmd
    # - More-detail.qmd


bibliography: references.bib



format:
  html:
    number-offset: [18, 5]
    number-depth: 1
    theme: flatly
    css: styles.css
  pdf:
    documentclass: scrreprt



