---
title: "Lessons in Statistical Thinking"
format:
    pdf: 
      default
toc: true
number-sections: true
number-offset: [18, 5]
in-header: latex-macros.tex
---

\newpage

```{r child="Reading-notes-lesson-19.qmd"}
```

\newpage


```{r child="Reading-notes-lesson-20.qmd"}
```

\newpage


```{r child="Reading-notes-lesson-21.qmd"}
```

\newpage


```{r child="Reading-notes-lesson-22.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-23.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-24.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-25.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-26.qmd"}
```


\newpage

```{r child="Reading-notes-lesson-28.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-29.qmd"}
```


\newpage

```{r child="Reading-notes-lesson-30.qmd"}
```


\newpage

```{r child="Reading-notes-lesson-31.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-32.qmd"}
```


\newpage

```{r child="Reading-notes-lesson-33.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-34.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-35.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-36.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-37.qmd"}
```

\newpage

```{r child="Reading-notes-lesson-38.qmd"}
```
